include::../../templates/ovm-header.adoc[]
:ovm-code: IT-BS-LE-LS-1.1
:kind: Lernsituation
:short-title: Linux Essentials 1
= {kind} {ovm-code} {short-title}
André Bauer <a.bauer@ovm-kassel.de>
v1.0, 19. Februar 2018

include::../../templates/ovm-head-table.adoc[]

| *Links*
| Kurs https://www.netacad.com/courses/ndg-linux-essentials/[NDG Linux Essentials]

| *Verwandte Literatur*
| IT-BS-LE-INFO-1.1 +
 https://www.lpice.eu/de/unsere-zertifizierungen/linux-essentials-ueberblick/lernziele-010/#c6080[Lerniele der Linux Essentials Prüfung 010]

| *Lizenz*
| {cc-by-sa}
|===

== Vorbereitung

. Melde dich bei der Cisco Networking Academy in den Kurs https://www.netacad.com/courses/ndg-linux-essentials/[NDG Linux Essentials] an.

. Lies das Informationsblatt IT-BS-LE-INFO-1.1.

. Installiere Virtualbox und richte eine Virutelle Maschine mit Ubuntu-Linux ein.
+
IMPORTANT: Das benötigte ISO-Image der Linux-Distribution Ubuntu 16.04.3 LTS steht im Intranet über das Netzlaufwerk `\\ovm-nas\bfi_19` bereit. +
Bitte lade dieses *nicht* aus dem Internet.

== Aufgaben

. Bearbeite im Lehrgang NDG Linux Essentials der Cisco Networking Academy die Module 1-8 bis zum Ende der Woche.

. Dokumentiere täglich in deinem E-Portfolio, was du bearbeitet hast, d.h. welche Module (und welche Chapter, Labs und Exams). Notiere auch, welches zusätzliche Material du verwendet hast.

. Dokumentiere ggf. erstellte Shell-Skripte in deinem E-Portfolio.

. Dokumentiere am Ende der Themenwoche in deinem E-Portfolio, welche https://www.lpice.eu/de/unsere-zertifizierungen/linux-essentials-ueberblick/lernziele-010/#c6080[Lerniele der Linux Essentials Prüfung 010] du erreicht hast.