include::partials/ovm-header.adoc[]
:ovm-code: IT-AE-UML-INFO-3.2
:kind: Information
:short-title: Das Verfahren nach Abbott
:prefix: abbott
include::partials/author.adoc[]
:revdate: 25. Februar 2018

// This work is licensed under a
// Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
// License.
// Authors: 
// Informatikreferendare und ehemalige Informatikreferendare der
// Studienseminare (heute ZfsL) Arnsberg, Hamm und Solingen. +
// Die Urheberin der Zusammenfassung des Verfahrens nach Abbott ist
// unbekannt.
// Some modifications by André Bauer
// Source:
// http://ddi.uni-wuppertal.de/material/materialsammlung/oberstufe/allgemein/abbott/info_01_verfahren_abbott.pdf

include::partials/ovm-head-table.adoc[]

| *Autoren des Orginaldokuments*
a|

[small]#Informatikreferendare und ehemalige Informatikreferendare der
Studienseminare (heute ZfsL) Arnsberg, Hamm und Solingen. +
Die Urheberin der Zusammenfassung des Verfahrens nach Abbott ist
unbekannt, dieses wird hier in leicht veränderter Form wiedergegeben.#

| *Orginaldokument*
| [small]#http://ddi.uni-wuppertal.de/material/materialsammlung/oberstufe/allgemein/abbott/info_01_verfahren_abbott.pdf#

| *Links*
| {empty}

| *Verwandte Literatur*
| IT-AE-UML-INFO-3.1

| *Lernjobs*
| IT-AE-UML-LJ-3.1 bis 3.4

| *Lizenz*
| {cc-by-nc-sa}
|===

= {short-title}

Auf Russell J. Abbott geht ein Verfahren zurück, das für die 
objektorientierte Analyse (_OOA_) bzw. objektorientierte Modellierung 
(_OOM_) hilfreich sein kann. 
Es folgt eine Zusammenfassung der drei erforderlichen 
Schritte.

****
Um aus einer umgangssprachlich formulierten Problembeschreibung die Objekte mit
den zugehörigen Attributen und Methoden (s.{nbsp}u.) zu erarbeiten,
geht man wie folgt vor:

. *Substantive (Hauptwörter) und Eigennamen herausfiltern* +
  Die Hauptwörter sind mögliche _Objekte_.
  Meist nicht beachtet werden allerdings Mengen- und Größenangaben 
  (»Kilogramm«), Sammelnamen (»Regierung«), 
  Materialbezeichnungen (»Plastik«) und abstrakte Begriffe 
  (»Liebe«, »Arbeit«).
  Zeitwörter (Verben), die als Hauptwörter benutzt werden (»das Betrachten 
  eines Bildes«) werden behandelt wie die zugehörigen Zeitwörter.
  Gattungsnamen wie z.{nbsp}B. »Kraftfahrzeug«, »Säugetier« und 
  »Einwohner« sind ebenfalls meist keine Objekte.

. *Verben (Zeitwörter) herausfiltern* +
  Sie bezeichnen häufig die Aktionen, welche von Objekten ausgeführt
  werden können, bzw. die Nachrichten, die diesen gesendet werden können,
  die sogenannten _Methoden_ der Objekte.
  Es ist festzustellen, welchem Objekt die Methode zugeordnet werden kann.

. *Adjektive (Eigenschaftswörter) herausfiltern* +
  Sie bezeichnen häufig die »Ausprägungen« (_Attributwerte_), 
  welche bestimmte Eigenschaften (die _Attribute_) von Objekten annehmen 
  können. Beispielsweise wäre »ledig« ein Attributwert zum Attribut 
  »Familienstand« oder »1216« der Attributwert des Attributs 
  »Seitenzahl« des aktuellen Dudens.
  Auch hier ist wieder festzustellen, welchem Objekt der Attributwert
  zugeordnet und wie das zugehörige Attribut bezeichnet werden kann.
****

Die grafische Darstellung von Objekten erfolgt durch Rechtecke. 
Die erste Zeile beeinhaltet dabei den eindeutigen Namen des Objekts und
durch einen Doppelpunkt getrennt den Namen der Klasse.
Diese Zeile wird unterstrichen.
Nach einer horizontalen Trennlinie folgen zeilenweise die Attribute mit ihren 
jeweiligen Attributwerten.
Die Methoden der Objekte sind (sofern vorhanden) von den Attributen und 
Attributwerten wiederum durch eine horizontale Linie getrennt.
Oft wird aber in Objektdiagrammen auf die Darstellung der Methoden
verzichtet. diese werden dann nur im Klassendiagramm notiert.

.Beispiel für ein Objekt
[graphviz, {prefix}-objekt, {graphviz-format}]
....
digraph G {
    fontname = "Bitstream Vera Sans";
    fontsize = 8;
    rankdir = BT;

    node [
        fontname = "Bitstream Vera Sans"
        fontsize = 8
        shape = "record"
	width = 3.5
    ];

    P1 [ label=<{<u align="left">gustavsRadiowecker: Radiowecker</u>|weckzeit = 06:30 Uhr<br align="LEFT"/>aktiv = AN|einschalten()<br/>ausschalten()<br/>alarmAuslösen()}> ];

//   P2 [ label="gustavsRadiowecker: Radiowecker\l|weckzeit = 06:30 Uhr\laktiv = AN\l|einschalten()\lausschalten()\lalarmAuslösen()\l" ];
}
....

// .Beispiel für ein Objekt
// [plantuml]
// ....
// object "<u>gustavsRadiowecker: Radiowecker</u>" as gr {
//   weckzeit = 06:30 Uhr
//   aktiv = AN
// }
// ....

_Bezeichner_ für Objekte, Attribute und Methoden beginnen
mit einem Kleinbuchstaben. 
Es ist in Java üblich, bei zusammengesetzten Bezeichnern neu einsetzende 
Worte durch Großbuchstaben hervorzuheben (siehe Beispiel).
Diese Schreibweise wird auch als
https://de.wikipedia.org/wiki/Binnenmajuskel#Programmiersprachen[camel case]
bezeichnet.