include::partials/ovm-header.adoc[]
:ovm-code: IT-AE-UML-LJ-3.3
:kind: Lernjob
:short-title: Objekt- und Klassendiagramme auf der Basis einer Situationsbeschreibung erstellen
include::partials/author.adoc[]
:revdate: 25. Februar 2018
:!sectnums:

include::partials/ovm-head-table.adoc[]

| *Links*
a|

Zum Erstellen von UML-Diagrammen bieten sich die Programme
https://wiki.gnome.org/Apps/Dia/[Dia],
https://www.draw.io/[draw.io],
http://www.yworks.com/products/yed[yEd] bzw.
https://www.yworks.com/yed-live/[yEd Live] und
http://plantuml.com/[PlantUML] an, dieses kann in u.{nbsp}a. in
https://en.wikipedia.org/wiki/PlantUML#Applications_that_use_PlantUML[Eclipse und Word als Plugin verwendet werden].

| *Verwandte Literatur*
| IT-AE-UML-INFO-3.1 bis 3.3

| *Lizenz*
| {cc-by-sa}
|===

= {short-title}

.Situationsbeschreibung
****
Carl hört zur Zeit gerne diese Lieder:

* Shape Of You - Ed Sheeran

* Unforgettable - French Montana feat. Swae Lee

* Something Just Like This - The Chainsmokers & Coldplay

* Galway Girl - Ed Sheeran

* Swalla - Jason Derulo feat. Nicki Minaj & Ty Dolla $ign

* Thunder - Imagine Dragons


Sophias Lieblingslieder sind gerade:

* Shape Of You - Ed Sheeran

* OK - Robin Schulz feat. James Blunt

* Galway Girl - Ed Sheeran

* Thunder - Imagine Dragons

* There's Nothing Holdin' Me Back - Shawn Mendes

Sophia und Carl wollen bei ihrem nächsten Treffen nur ihre gemeinsamen
Lieblingslieder hören, und erstellen dazu eine passende Playlist.
****

== Aufgabe 1

Erstellen Sie anhand der Situationsbeschreibung ein Objektdiagramm.

== Aufgabe 2

Erstellen Sie auf der Grundlage Ihres Objektdiagramms ein Klassendiagramm.
Ergänzen Sie sinnvolle Methoden und ggf. Klassen, die für die
objektorientierte Modellierung benötigt werden.