include::partials/ovm-header.adoc[]
:ovm-code: IT-AE-UML-LJ-3.4
:kind: Lernjob
:short-title: UML-Diagramme auf der Basis einer User-Story erstellen
:author: André Bauer <a.bauer@ovm-kassel.de>
:revdate: 21. Februar 2018
:!sectnums:

include::partials/ovm-head-table.adoc[]

| *Links*
a|

Zum Erstellen von UML-Diagrammen bieten sich die Programme
https://wiki.gnome.org/Apps/Dia/[Dia],
https://www.draw.io/[draw.io],
http://www.yworks.com/products/yed[yEd] bzw.
https://www.yworks.com/yed-live/[yEd Live] und
http://plantuml.com/[PlantUML] an, dieses kann in u.{nbsp}a. in
https://en.wikipedia.org/wiki/PlantUML#Applications_that_use_PlantUML[Eclipse und Word als Plugin verwendet werden].

| *Verwandte Literatur*
a|

* IT-AE-UML-INFO-3.1
* IT-AE-UML-INFO-3.2
* IT-AE-UML-INFO-3.3


| *Lizenz*
| {cc-by-sa}
|===

= {short-title}

.User-Story
****
Anastasia stellt bei ihren Internet-Radiowecker die Weckzeit auf 6:25{nbsp}Uhr,
wählt das Programm super-harmony.fm aus, aktiviert den Wecker und legt sich
schlafen.
Um 0:25{nbsp}Uhr synchronisiert der Wecker seine Uhrzeit mit einem
NTP-Server.
Als der Wecker am nächsten Morgen um 6:25{nbsp}Uhr beginnt, das
Radioprogramm
von super-harmony.fm zu streamen, drückt sie auf die Slummertaste, der
Wecker schweigt und Anastasia schläft weiter.
Als der Wecker nach 5{nbsp}Minuten
wieder Musik spielt, liest Anastasia die Zeit 6:30{nbsp}Uhr vom Display ab,
schaltet sie die Weckfunktion aus und stellt den Sender auf
pure-techno.fm um. Nachdem sie sich umgezogen hat, schaltet sie das Radio
wieder aus.
****

== Aufgabe 1

Erstellen Sie zu der User-Story ein geeignetes Sequenzdiagramm.

== Aufgabe 2

Fertigen Sie zu der User-Story _zwei_ Objektdiagramme an, die jeweils
den Zustand der in der User-Story vorkommenden Objekte und Personen
zu unterschiedlichen Zeitpunkten wiedergeben.

== Aufgabe 3

Erstellen Sie zu der User-Story ein Klassendiagramm auf der Grundlage
Ihres Ergebnisses aus Aufgabe 2.
Ergänzen Sie sinnvolle Methoden und, falls benötigt, zusätzliche Klassen wie
z.{nbsp}B. eine Enumeration. 

// == Aufgabe 4

// Geben Sie zu ihrem Klassendiagramm aus Aufgabe 3 den entsprechende
// Java-Quellcode an.


