= Shell-Sessions mit Asciidoctor dokumentieren <1>
André Bauer <2>
13. Mai 2018 <3>

Shell-Sessions, die mit Script aufgezeichnet wurden, 
werden mit vier Strichen (Minuszeichen bzw. "dash")
als Sourcecode-Block mit vorformatiertem Text
eingerahmt.
<4>
Zusätzlich kann mit der Angabe `[source, sh]` die <5>
Sprache angegeben werden. Hier ein Beispiel:

[source,sh] <6>
pass:[----] // <7>
user@ubuntu-vb:~$ cd srv/
user@ubuntu-vb:~/srv$ ls
index.adoc  index.html  index.pdf  inheritance.svg
user@ubuntu-vb:~/srv$ touch diagramme.adoc pass:[<1>] <8>
user@ubuntu-vb:~/srv$ echo "= Diagramme mit Asciidoctor" >> diagramme.adoc 
user@ubuntu-vb:~/srv$ cat diagramme.adoc 
= Diagramme mit Asciidoctor 
pass:[----]
<1> Erzeugt die Datei `diagramme.adoc`. <9>

== Generieren einer HTML5-Datei <10>

Ein AsciiDoc-Dokument wird dann mit dem folgenden Befehl in eine
HTML-Datei umgewandelt.

[source,sh] 
pass:[----]
$ asciidoctor -r asciidoctor-diagram -b html index.adoc  
pass:[----]

== Anzeigen mit Firefox

Mit `firefox index.html` wird diese im Browser angezeigt.
