include::partials/ovm-header.adoc[]
:ovm-code: IT-BS-VM-LJ-3.1
:kind: Lernjob
:short-title: Dokumentieren mit Script und AsciiDoc
:experimental:
:prefix: dsa
include::partials/author.adoc[]
:revdate: 22. Mai 2018
:stem: latexmath

include::partials/ovm-head-table.adoc[]

| *Lizenz*
| {cc-by-sa}
|=== 

= {short-title}

{empty}

== Shell-Sessions mit Script documentieren

Shell-Sessions können unter Linux mit
dem Programm Script aufgezeichnet werden.

.Aufzeichnung einer Shell-Session mit Script
====
[source]
----
$ script session1.log <1>
Skript gestartet, die Datei ist session1.log
$ ssh user@192.168.178.28 
user@192.168.178.28's password: 
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.10.0-28-generic x86_64)

Last login: Thu May 10 18:58:28 2018 from 192.168.178.21
user@ubuntu-vm:~$ ls
Bilder     Downloads  Öffentlich    srv     Vorlagen
Dokumente  Musik      Schreibtisch  Videos
user@ubuntu-vm:~$ Abgemeldet <2>
Connection to 192.168.178.28 closed.
[user@hostsystem ~]$ exit <3>
exit
Skript wurde beendet, die Datei ist session1.log 
----
<1> Startet Script und speichert die Aufzeichnung in der
    Datei `session1.log`.
<2> Die SSH-Session wird mit kbd:[Strg+D] oder `exit` beendet.   
<3> Script wird mit `exit` beendet.    
====

Das Ergebnis kann mit `cat` angezeigt werden oder mit
einem Texteditor wie z.{nbsp}B. GNU nano, gedit,
emacs, vim, atom oder anderen bearbeitet, kommentiert
und z.{nbsp}B. Teil eines AsciiDoc-Dokuments werden (s.{nbsp}u.). 

.Ausgabe der mit Script gespeicherten Shell-Session
====
[source, sh]
----
$ cat session1.log 
Script started on 2018-05-11 08:03:35+02:00
[user@hostsystem ~]$ ssh user@192.168.178.28
user@192.168.178.28's password: 
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.10.0-28-generic x86_64)

Last login: Thu May 10 18:58:28 2018 from 192.168.178.21
user@ubuntu-vm:~$ ls
Bilder     Downloads  Öffentlich    srv     Vorlagen
Dokumente  Musik      Schreibtisch  Videos
user@ubuntu-vm:~$ Abgemeldet
Connection to 192.168.178.28 closed.
[user@hostsystem ~]$ exit
exit

Script done on 2018-05-11 08:04:13+02:00
----
====

:!sectnums:
=== Monochrome Ausgabe der Shell
:sectnums:

[NOTE]
====
In vielen Linux-Distributionen enthält die Ausgabe im Terminal farbige
Hervorhebungen. Diese führen zur Ausgabe von unerwünschten Zeichen
in den Log-Dateien von Script. Die farbige Ausgabe wird in der
Konfigurationsdatei der Shell gesteuert. Bei der Bash ist `~/.bashrc`
diese Konfigurationsdatei. 
Um die farbige Ausgabe von Script zu unterbinden müssen mit einem
Texteditor wie `nano` zwei Zeilen verändert werden.
Änderungen in der `~/.bashrc` sind in allen neu gestarteten Terminals wirksam.
In dem aktuellen Terminal können sie durch `source` aktiviert werden:

[source,sh]
----
$ source ~/.bashrc
----   
====

Im Folgenden werden die beiden Stellen in der Datei `~/.bashrc` gezeigt,
die geändert werden müssen.

.Ursprüngliche `~/.bashrc`
[source,sh]
----
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\0
33[01;34m\]\w\[\033[00m\]\$ ' <1>
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ ' <2>
fi
----
<1> Setzt einen farbigen Prompt.
<2> Setzt einen monochromen Prompt.

.Geänderte `~/.bashrc`
[source,sh]
----
if [ "$color_prompt" = yes ] && false; then <1>
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\0
33[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
----
<1> Durch Einfügen von `&& false` wird stets der monochrome Prompt ausgewählt.

.Ursprüngliche `~/.bashrc`
[source,sh]
----
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto' <1>
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
----
<1> Hier wir ein Alias für eine farbige Ausgabe mit `ls` gesetzt.

.Geänderte `~/.bashrc`
[source,sh]
----
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ] && false; then <1>
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
----
<1> Das Setzen der Aliasse wird durch Einfügen von `&& false` unterbunden.

.Ursprüngliche `~/.bashrc`
[source,sh]
----
# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1" <1>
    ;;
*)
    ;;
esac
----
<1> Diese Anweisung ist für die Terminals in Ubuntu unnötig, führt aber
    dazu, dass bei Script der Prompt `user@host:dir` doppelt erscheint.

.Ursprüngliche `~/.bashrc`
[source,sh]
----
# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
#    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1" <1>
    ;;
*)
    ;;
esac
----
<1> In Shell-Scripts wird durch ein `#` am Zeilenanfang, diese Zeile
    {ldquo}auskommentiert{rdquo} und dadurch nicht mehr ausgeführt.
    Der Prompt `user@host:dir` erscheint nun in den Aufzeichnungen
    mit Script nur noch einfach.

:!sectnums:
=== Aufgabe {counter:a}
:sectnums:

****
Starten Sie die Aufzeichnung einer Shell-Session mit Script in einer
Linux-VM und führen Sie die folgenden Arbeitschritte durch:

. Erstellen Sie den Ordner `script_docs` mit `mkdir`.
. Legen Sie in diesem Ordner die Dateien `hello.adoc` und `ad.adoc`
  mit `touch` an.
. Fügen Sie `"Hallo Script"` der Datei `hello.adoc` mit
  `echo "Hallo Script" >> script_docs/hello.adoc` an.
. Fügen Sie der Datei `ad.adoc` die Zeile `"= Asciidoctor"` an.
. Lassen Sie mit `ls -l` den Inhalt des Ordners `script_docs` ausgeben
  und beenden Sie Script.

Überprüfen Sie anschließend mit `cat`, ob die Aufzeichnung erfolgreich war.
****

== AsciiDoc

https://de.wikipedia.org/wiki/AsciiDoc[AsciiDoc] ist eine
leichtgewichtige Markup-Sprache, wie z.{nbsp}B. auch
https://de.wikipedia.org/wiki/Markdown[Markdown]. +
http://asciidoctor.org[Asciidoctor] ist eine Ruby-Anwendung,
die AsciiDoc-Dokumente in HTML5, PDF und andere Formate
umwandelt.

Ein AsciiDoc-Dokument wird mit einem Texteditor wie GNU nano, gedit,
emacs, vim, atom oder anderen verfasst bzw. bearbeitet
-- Textverarbeitungsprogramme wie Word oder Writer sind nicht geeignet.
Anschließend werden die AsciiDoc-Dateien in
ein Ausgabeformat übersetzt wie PDF, HTML5, Docbook oder andere.

=== Installation von Asciidoctor

Für Asciidoctor wird das Paket `ruby` benötigt:

[source, sh]
----
$ sudo apt update
$ sudo apt install ruby
----

Mit dem Paket `ruby` wird auch
https://de.wikipedia.org/wiki/RubyGems[RubyGems],
das Paketsystem für Ruby installiert, dass zur Installation von
`asciidoctor` verwendet wird.


[source,sh]
----
$ sudo gem install asciidoctor asciidoctor-diagram <1>
$ sudo apt update
$ sudo apt install plantuml graphviz
$ mkdir srv
$ cd srv
$ nano index.adoc <2>
$ asciidoctor -r asciidoctor-diagram -b html index.adoc <3>
----
<1> Installation von Asciidoctor und Asciidoctor Diagram mit RubyGems.
<2> Erstellen eines AsciiDoc-Dokuments.
<3> Mit `-r asciidoctor-diagram` wir die Erweiterung
    https://asciidoctor.org/docs/asciidoctor-diagram/[Asciidoctor Diagram]
    verwendet.							  

<<<

=== Erste Schritte

Die wichtigsten Formatierungen werden anhand des folgenden Beispiels
erläutert.

.Beispiel für ein AsciiDoc-Dokument
====

[source,asciidoc,subs=+macros]
----
include::{pub_dir}/betriebssysteme/netzwerke-mit-virtualbox/asciidoc-basis-beispiel-code.adoc[] 
----
<1> Der Dokumententitel wird zu Beginn des Dokuments mit einem `=`-Zeichen angegeben.
<2> Die Angabe des Autors folgt in der Zeile nach dem Dokumententitel.
<3> Das Datum wird direkt in der Zeile nach dem Autor angegeben.
<4> Abschnitte werden durch Leerzeilen getrennt.
<5> Mit Akzentzeichen (backticks) wird der Text für Kommandos oder
    Sourcecode-Ausschnitte in
    https://de.wikipedia.org/wiki/Nichtproportionale_Schriftart[Festbreitenschrift]
    gesetzt.
<6> In den eckigen Klammern kann nach der Angabe `source`
    die verwendete Sprache, wie z.{nbsp}B. `java` oder `sh` für Shell,
    eingetragen werden. Dadurch wir die
    https://de.wikipedia.org/wiki/Syntaxhervorhebung[Syntax farblich hervorgehoben].
<7> Shell-Befehle bzw. Source-Code-Blöcke werden mit mit vier Minuszeichen
    (dash) als vorformatierter Text gekennzeichnet bzw. eingerahmt.
<8> Callout-Nummern werden im Source-Code-Block mit eckigen Klammern am Ende der
    Zeile eingetragen, d.{nbsp}h. `<1>, <2>` usw. 
<9> Callouts werden direkt nach dem Source-Code-Block erläutert. 
<10> Überschriften werden mit zwei oder mehreren `=`-Zeichen eingeleitet.
====

Das AsciiDoc-Dokument wird anschließend mit dem im Beispiel angegebenen
Kommando übersetzt und kann dann im Browser angezeigt werden.

.Browserdarstellung eines mit Asciidoctor generieten HTML5-Dokumentes
====
image::asciidoc-basis-beispiel.svg[]
====

Weitere Informationen, wie man ein AsciiDoc-Dokument gestalten kann,
stehen im
https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer’s Guide]
und im
https://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual].


:!sectnums:
=== Aufgabe {counter:a}
:sectnums:

****
Erstellen Sie aus der aufgezeichneten Shell-Session aus Aufgabe 1 ein
AsciiDoc-Dokument, indem Sie Titelangaben und Erläuterungen hinzufügen
sowie die Shell-Kommandos als Sourcecode-Blöcke kennzeichen und
Callouts einfügen.
Generieren Sie mit Asciidoctor aus der AsciiDoc-Datei eine HTML5-Datei
und überprüfen Sie das Ergebnis im Browser.
****

=== Diagramme mit Asciidoctor erstellen

Über die Erweiterung
https://asciidoctor.org/docs/asciidoctor-diagram/[Asciidoctor Diagram]
können Diagram-Beschreibungen
direkt in AsciiDoc-Dokumente eingebettet werden. Asciidoctor sorgt dann
automatisch für die Übersetzung und fügt die erzeugten Grafiken dann als
Bilder ein. Vorraussetzung ist, dass die dazu notwendigen Programme
installiert sind.

==== PlantUML

http://plantuml.com/[PlantUML] ist eine Werkzeug, um (UML-)Diagramme zu
erstellen. Über die Erweiterung Asciidoctor Diagram kann man
PlantUML-Diagramme direkt in AsciiDoc-Dokumenten beschreiben.
Diese werden in
https://de.wikipedia.org/wiki/Portable_Network_Graphics[PNG-Grafiken] oder
https://de.wikipedia.org/wiki/Scalable_Vector_Graphics[SVG-Grafiken]
übersetzt.

Für PlantUML gibt es u.{nbsp}a. Plug-Ins für
http://plantuml.com/eclipse[Eclispe] und
https://plugins.jetbrains.com/plugin/7017-plantuml-integration[Jet Brains IDEs wie IntelliJ IDEA].

:sectnums!:

.Beispiel für die Verwendung von PlantUML in einem AsciiDoc-Dokument und Ausgabe im Browser
====

[cols="70h,~",frame=none]
|===
| AsciiDoc | Darstellung im Browser

a|

[source,asciidoc]
-----
== Assoziation zwischen den Klassen A und B

[plantuml, class-association, svg] <1>
.... <2>
class A

class B

A -up-> B 
....

-----
<1> In den eckigen Klammern wird das Diagrammwerkzeug, der Dateiname und
    das Zielformat festgelegt. Hier wird die Diagramm-Beschreibung mit PlantUML
    in eine SVG-Grafik übersetzt und in der Datei `class-association.svg` 
    gespeichert.     
<2> Diagramm-Beschreibungen werden als Block mit vier Punkten eingerahmt. 

a|

[discrete]
== Assoziation zwischen den Klassen A und B

image::{prefix}-class-association.svg[]

|===

====

:sectnums:

Die Diagramm-Beschreibungs-Sprache von PlantUML ist anhand zahlreicher
Beispiel unter
http://plantuml.com/[PlantUML.com] sowie im
http://plantuml.com/PlantUML_Language_Reference_Guide.pdf[PlantUML Language Reference Guide]
dokumentiert.

==== blockdiag, actdiag, nwdiag und seqdiag

Die Programme
http://blockdiag.com/en/[blockdiag, seqdiag, actdiag und nwdiag]
übersetzen --{nbsp}ähnlich wie PlantUML{nbsp}-- Diagramm-Beschreibungen
in Grafiken.

Sie können unter Ubuntu über das Paketmanagment-System installiert werden:

----
$ sudo apt update
$ sudo apt install python-blockdiag python-actdiag python-nwdiag python-seqdiag
----

<<<

:!sectnums:
==== Aufgabe {counter:a}
:sectnums:

[cols="70h,~"]
|===

a|

Fügen Sie Ihrem AsciiDoc-Dokument aus den Aufgaben 1 und 2 eine
Diagramm-Beschreibung für die nebenstehende Grafik
mit PlantUML hinzu und lassen Sie
Asciidoctor daraus ein HTML5-Dokument mit SVG-Grafik erstellen.

Hilfe zum Erstellen einer solchen
Grafik finden Sie unter http://plantuml.com/deployment-diagram[].

a|

image::{prefix}-plantuml-deployment.svg[]

|===

=== PDF-Dokumente generieren

PDF-Dokumente werden aus Asciidoc-Dokumenten mit der Erweiterung
https://asciidoctor.org/docs/asciidoctor-pdf/[Asciidoctor PDF]
durch Angabe von `-r asciidoctor-pdf` und des Ausgabeformats mit `-b pdf`
generiert.

==== Installation

[source, sh]
----
$ sudo gem install asciidoctor-pdf --pre
----

==== Anwendung

[source, sh]
----
$ asciidoctor -r asciidoctor-diagram -r asciidoctor-pdf -b pdf -a allow-uri-read index.adoc
----

Für PDF-Dokumente gibt es unter Linux verschiedenen Viewer wie `evince`
oder `atril`, die die Dokumente nach Änderungen automatisch neu laden.

[source, sh]
----
$ evince index.pdf &
----

:!sectnums:
==== Aufgabe {counter:a}
:sectnums:

****
Generieren Sie aus Ihrem AsciiDoc-Dokument aus den Aufgaben 1-3 eine PDF-Datei,
die Sie in Ihr E-Portfolio einbinden.
****