include::../../templates/ovm-header.adoc[]
:ovm-code: IT-AE-JA-INFO-5.3
:kind: Information
:short-title: Objektorientierte Modellierung (OOM)
:prefix: oom
= {kind} {ovm-code} {short-title}
André Bauer <a.bauer@ovm-kassel.de>
v1.0, 25. Februar 2018
//:toc: macro
//:toclevels: 4

include::../../templates/ovm-head-table.adoc[]

| *Links*
| https://de.wikipedia.org/wiki/Objektorientierte_Analyse_und_Design[Wikipedia: Objektorientierte Analyse und Design]

| *Verwandte Literatur*
| IT-AE-JA-INFO-5.2

| *Lernjobs*
| IT-AE-JA-LJ-5.*

| *Lizenz*
| {cc-by-sa}
|===

== {short-title}

//toc::[]

In der objektorientierten Modellierung werden u.{nbsp}a. die
bereits vorgenommenen Modellierungen in den Klassendiagrammen
verfeinert und z.{nbsp}B. Datentypen, initiale Werte und weitere
Methoden eingefügt.
Gegebenenfalls werden die Diagramme um weitere Klassen ergänzt,
die sich nicht unmittelbar aus der Analyse ergeben haben, aber für
die Implementierung in der gewählten Programmiersprache benötigt werden,
wie die Definition einer Enumeration.

=== Enumerations

[[objektdiagramm-1]]
.Objektdiagramm für einen Aufbau mit einem Schalter und drei Lampen zu Beginn der User-Story-1
[plantuml, {prefix}-objektdiagramm-schalter-drei-lampen-1, svg]
....
object "<u>schalter1: Schalter</u>" as schalter1 {
  zustand = AUS
} 

object "<u>lampe1: Lampe</u>" as lampe1 {
  zustand = AUS
} 

object "<u>lampe2: Lampe</u>" as lampe2 {
  zustand = AUS
} 

object "<u>lampe3: Lampe</u>" as lampe3 {
  zustand = AUS
}

lampe1 <- schalter1 : schaltet

schalter1 -> "     schaltet" lampe3

schalter1 -> lampe2 : schaltet
....

[[objektdiagramm-2]]
.Objektdiagramm für einen Aufbau mit einem Schalter und drei Lampen zum Ende der User-Story-1
[plantuml, {prefix}-objektdiagramm-schalter-drei-lampen-2, svg]
....
object "<u>schalter1: Schalter</u>" as schalter1 {
  zustand = EIN
} 

object "<u>lampe1: Lampe</u>" as lampe1 {
  zustand = EIN
} 

object "<u>lampe2: Lampe</u>" as lampe2 {
  zustand = EIN
} 

object "<u>lampe3: Lampe</u>" as lampe3 {
  zustand = EIN
} 

lampe1 <- schalter1 : schaltet

schalter1 -> "     schaltet" lampe3

schalter1 -> lampe2 : schaltet
....

In den Objektdiagrammen in <<objektdiagramm-1>> und <<objektdiagramm-2>>
haben die Objekte das
Attribut `zustand` mit den möglichen Werten `ON` und `OFF.`
Anstatt eines vorhandenen Java-Datentyps wie `int`, `boolean` oder `string`
erstellen wir mithilfe einer Aufzählung (engl. enumeration, in Java abgekürzt
zu `enum`)
einen passenden neuen und aussagekräftigen Datentyp.

[[listing-enum-state]]
.Enumumertation State in Java
[source,java]
----
enum State {
  ON,
  OFF
}
----

Die Aufzählung `State` ergänzen wir in dem Klassendiagramm und
verwenden zudem ab jetzt englische Begriffe. Die Verwendung englischer
Sprache im Quellcode ist üblich, da bei den meisten Programmiersprachen
für die Sprachelemente sowie die
https://de.wikipedia.org/wiki/Programmbibliothek[Programmbibliotheken]
ohnehin englische Sprache verwendet wird, wie auch bei Java.
`Switch` und `Lamp` erhalten beide `OFF` als initialen Wert für `state`.

[[klassendiagramm-2]]
.Klassendiagramm mit Enumeration und englischen Begriffen
[plantuml, {prefix}-klassendiagramm-schalter-lampe-enum, svg]
....
class "Switch" as switch1 {
  state: State = OFF
  press()
} 

class "Lamp" as lamp1 {
  state: State = OFF
  turnOn()
  turnOff()
}

class "State" << enum >> 
note right
  Eine Enumeration wird in
  Klassendiagrammen mit «enum»
  als besondere Klasse gekennzeichnet.
end note
  
switch1 "1  " --> "*" lamp1 : controls
switch1 -> State
lamp1 -> State
....

Sowohl `Switch` als auch `Lamp` verwenden `State`, was durch Pfeile
in <<klassendiagramm-2>> gekennzeichnet ist.

=== Objekte und Beziehungen zwischen Objekten erstellen

Um Objekte einer Klasse zu erstellen, wird ein sogenannter Konstruktor
benötigt. In Java sind Konstruktoren besondere Methoden, die
denselben Namen wie die Klasse tragen. Sie können Paramter haben,
um z.{nbsp}B. Attribute zu initialisieren.
In unserem Beispiel erhält `Switch` den Konstruktor `Switch()` und
`Lamp` den Konstruktor `Lamp()`, also jeweils ohne Parameter.

Um die Beziehungen zwischen Objekten der Klasse `Lamp` und einem
Objekt der Klasse `Switch` herzustellen bzw. auch wieder zu lösen,
werden zusätzliche Methoden in `Switch` benötigt, für die wir mit
`connect` bzw. `disconnect` möglichst passende Namen wählen.
Sie haben beide einen Parameter mit dem Datentyp `Lamp`.


[[klassendiagramm-3]]
.Klassendiagramm mit Enumeration und englischen Begriffen
[plantuml, {prefix}-klassendiagramm-schalter-lampe-enum-erweitert, svg]
....
class "Switch" as switch1 {
  state: State = OFF
  Switch()
  press()
  connect(Lamp)
  disconnect(Lamp)
} 

class "Lamp" as lamp1 {
  state: State = OFF
  Lamp()
  turnOn()
  turnOff()
}

class "State" << enum >> 

switch1 "1  " --> "*" lamp1 : controls
switch1 -> State
lamp1 -> State
....

Damit haben wir aus den User-Stories eine objektorientierte Struktur
für die Software entworfen. Man nennt diesen Schritt
https://de.wikipedia.org/wiki/Objektorientierte_Analyse_und_Design[*objektorientierte Modellierung*].

=== Die Aggregation (Hat-Beziehung)

Neben der
https://de.wikipedia.org/wiki/Assoziation_(UML)[Assoziation (Kennt-Beziehung)]
gibt es noch stärkere Beziehungstypen, u.{nbsp}a. die
https://de.wikipedia.org/wiki/Assoziation_(UML)#Aggregation_und_Komposition[Aggregation (Hat-Beziehung)] zwischen
Objekten bzw. Klassen.
So _hat_ ein Motorrad ein Vorderrad.

[[objektdiagramm-aggregation]]
.Objektdiagramm mit Aggregation
[plantuml, {prefix}-objektdiagramm-aggregation, svg]
....
object "<u>motorrad1: Motorrad</u>" as m1 

object "<u>vorderrad1: Vorderrad</u>" as v1

m1 o-- v1
note on link
  Das Motorrad <i>hat</i> ein Vorderrad.
end note
....

Die Raute (auch Diamand genannt),
die diesen Beziehungstyp kennzeichnet, darf _nicht_ wie
die Pfeilspitze der Assoziation interpretiert werden, denn die Beziehung
geht vom Motorrad zum Vorderrad und nicht vom
Vorderrad zum Motorrad.
Auf der Ebene der Programmierung ist bei einer Aggregation die Klasse
Motorrad für die Verwaltung der Objekte der Klasse Vorderrad zuständig.