include::partials/ovm-header.adoc[]
:ovm-code: IT-AE-JA-INFO-5.1
:kind: Information
:prefix: oose
:short-title: Objektorientierte Software-Entwicklung 
:author: André Bauer <a.bauer@ovm-kassel.de>
:revdate: 25. Februar 2018

include::partials/ovm-head-table.adoc[]

| *Links*
| {empty}

| *Verwandte Literatur*
| {empty}

| *Lizenz*
| {cc-by-sa}
|===

= {short-title}

{empty}

Wenn eine Software mehr als etwa hundert Zeilen Quellcode umfasst,
spätestens ab mehreren hundert,
benötigt man Techniken, um der Software eine klare
Struktur zu geben. Eine klare Struktur ist wichtig, damit die Software leicht
angepasst und erweitert werden kann, sowohl durch bisherige als auch durch
andere Entwickler.

== Objektorientierte Analyse (OOA)

=== User-Stories

Eine sehr häufig angewandte Technik zum Entwurf und zur Strukturierung ist die
objektorientierte Software-Entwicklung. Dazu wird in der objektorientierten
Analyse anhand von Szenarien ermittelt, wie die zukünftige Nutzung des
(Software-)Systems ablaufen soll. Dabei werden sogenannte
https://de.wikipedia.org/wiki/User-Story[User-Stories]
verfasst:

[[user-story-1]]
.User-Story 1
[quote]
____
Die Lampen lampe1, lampe2 und lampe3 sind anfangs ausgeschaltet. Der Schalter schalter1
ist ebenfalls in der Positon {ldquo}aus{rdquo}.
Der Benutzer betätigt den Schalter schalter1. Die Lampen  lampe1, lampe2 und lampe3 werden
eingeschaltet.
____

Aus den User-Stories können nun die relevanten Objekte abgeleitet werden;
im Beispiel sind dies der Benutzer, der Schalter schalter1 sowie die Lampen lampe1, lampe2 und
lampe3.

=== Verfahren von Abbott

Mit dem Verfahren von Abbott werden aus einer Problem- oder
Situationsbeschreibung oder entsprechenden User-Stories
mögliche Objekte, Attribute und Methoden ermittelt.
Dieses Verfahren wird auf dem Informationsblatt IT-AE-JA-INFO-5.2
erläutert.

=== Sequenzdiagramme

Stellt man die User-Story in einem
https://de.wikipedia.org/wiki/Sequenzdiagramm[UML-Sequenzdiagramm] dar,
so kann man den Programmablauf entlang der Pfeile ablesen.
So sendet der Schalter schalter1 die Nachricht `einschalten()` an die Lampe lampe1. Erst
wenn diese den Einschaltvorgang abgeschlossen hat, setzt schalter1 seine Arbeit
fort und sendet lampe2 die Nachricht _einschalten()_ usw.

[[sequenzdiagramm-1]]
.Sequenzdiagramm zur <<user-story-1>>
[plantuml, {prefix}-sequenzdiagramm-1, svg]
....
actor Benutzer

Benutzer -> "schalter1: Schalter" as schalter1: drücken()

schalter1 -> "lampe1: Lampe" as lampe1: einschalten()
lampe1 --> schalter1

schalter1 -> "lampe2: Lampe" as lampe2: einschalten()
lampe2 --> schalter1

schalter1 -> "lampe3: Lampe" as lampe3: einschalten()
lampe3 --> schalter1

schalter1 --> Benutzer
....

Eine zweite User-Story vervollständigt die möglichen Anwendungsfälle
der Schaltung:

[[user-story-2]]
.User-Story 2
[quote]
____
Die Lampen lampe1, lampe2 und lampe3 sind eingeschaltet. Der Schalter schalter1
ist ebenfalls in der Positon {ldquo}ein{rdquo}.
Der Benutzer betätigt den Schalter schalter1. Die Lampen  lampe1, lampe2 und lampe3 werden
ausgeschaltet.
____

Daraus ergibt sich das folgende Sequenzdiagramm:

[[sequenzdiagramm-2]]
.Sequenzdiagramm zur <<user-story-2>>
[plantuml, {prefix}-sequenzdiagramm-2, svg]
....
actor Benutzer

Benutzer -> "schalter1: Schalter" as schalter1: drücken()

schalter1 -> "lampe1: Lampe" as lampe1: ausschalten()
lampe1 --> schalter1

schalter1 -> "lampe2: Lampe" as lampe2: ausschalten()
lampe2 --> schalter1

schalter1 -> "lampe3: Lampe" as lampe3: ausschalten()
lampe3 --> schalter1

schalter1 --> Benutzer
....

=== Objektdiagramme

Aus den User-Stories bzw. den zugehörigen Sequenzdiagrammen kann man
ablesen, wie die beteiligten Objekte miteinander verknüpt sein müssen,
um Nachrichten austauschen zu können:

Der Schalter schalter1 verwendet die Lampen lampe1, lampe2 und lampe3, um ihnen jeweils die
Nachricht `einschalten()` bzw. `ausschalten()` senden zu können.
Diese Beziehung wird in einem
https://de.wikipedia.org/wiki/Objektdiagramm[Objektdiagramm] durch Pfeile
dargestellt.

Objekte, die Nachrichten austauschen, werden im Diagramm mit Linien verbunden. 
Dieser Beziehungstyp wird _Assoziation_ genannt (auch Kennt-Beziehung).
Die Beziehungen werden mit einem Namen versehen, im Beispiel lautet dieser
{ldquo}schaltet{rdquo}.
Wenn die Nachrichten nur in eine Richtung ausgetauscht werden, wird
dies durch eine Pfeilspitze kenntlich gemacht.

Daraus ergibt sich das folgende Objektdiagramm:

[[objektdiagramm-1]]
.Objektdiagramm für einen Aufbau mit einem Schalter und drei Lampen zu Beginn der <<user-story-1>>
[plantuml, {prefix}-objektdiagramm-schalter-drei-lampen-1, svg]
....
object "<u>schalter1: Schalter</u>" as schalter1 {
  zustand = AUS
} 

object "<u>lampe1: Lampe</u>" as lampe1 {
  zustand = AUS
} 

object "<u>lampe2: Lampe</u>" as lampe2 {
  zustand = AUS
} 

object "<u>lampe3: Lampe</u>" as lampe3 {
  zustand = AUS
}
note right
  <u>Objektname : Klasse</u>
  
  --
  Attribut = Wert der Attributs
end note

lampe1 <- schalter1 : schaltet
note top on link
  Name der Beziehung
end note

schalter1 -> "schaltet" lampe3

schalter1 -> lampe2 : schaltet
....

Ein Objektdiagramm stellt den Zustand eines Software-Systems zu einen
bestimmten Zeitpunkt dar. +
Das Diagramm in <<objektdiagramm-1>> stellt den
Zustand zu Beginn der <<user-story-1>> bzw. zum Ende der
<<user-story-2>> dar, da der Schalter und die Lampen den Zustand `AUS` haben.

Der Zustand zum Ende der <<user-story-1>> bzw. zu Beginn der <<user-story-2>>
sieht so aus:

[[objektdiagramm-2]]
.Objektdiagramm für einen Aufbau mit einem Schalter und drei Lampen zum Ende der <<user-story-1>>
[plantuml, {prefix}-objektdiagramm-schalter-drei-lampen-2, svg]
....
object "<u>schalter1: Schalter</u>" as schalter1 {
  zustand = EIN
} 

object "<u>lampe1: Lampe</u>" as lampe1 {
  zustand = EIN
} 

object "<u>lampe2: Lampe</u>" as lampe2 {
  zustand = EIN
} 

object "<u>lampe3: Lampe</u>" as lampe3 {
  zustand = EIN
} 

lampe1 <- schalter1 : schaltet

schalter1 -> "schaltet" lampe3

schalter1 -> lampe2 : schaltet
....

Man könnte jetzt den Schalter und jede der
drei Lampen direkt programmieren, aber
dies hätte Nachteile:
für die Lampen würde man dreimal dasselbe Programm schreiben.
Es wäre daher eine unflexible Lösung, man möchte mit derselben
Software auch Schaltungen
mit vier oder mehr Lampen mit einem Schalter verbinden können.

[[objektdiagramm-b]]
.Objektdiagramm für einen Aufbau mit einem Schalter und fünf Lampen
[plantuml, {prefix}-objektdiagramm-schalter-fuenf-lampen, svg]
....
object "<u>schalter1: Schalter</u>" as schalter1 {
  zustand = AUS
} 

object "<u>lampe1: Lampe</u>" as lampe1 {
  zustand = AUS
} 

object "<u>lampe2: Lampe</u>" as lampe2 {
  zustand = AUS
} 

object "<u>lampe3: Lampe</u>" as lampe3 {
  zustand = AUS
} 

object "<u>lampe4: Lampe</u>" as lampe4 {
  zustand = AUS
} 

object "<u>lampe5: Lampe</u>" as lampe5 {
  zustand = AUS
} 


lampe1 <- schalter1 : schaltet

schalter1 -> "schaltet" lampe3

schalter1 -> lampe2 : schaltet

schalter1 -> lampe4 : schaltet

schalter1 -> lampe5 : schaltet
....

=== Klassendiagramme

Daher verallgemeinert man die möglichen Objektbeziehungen in Form eines
https://de.wikipedia.org/wiki/Klassendiagramm[UML-Klassendiagramms]:

[[klassendiagramm-1]]
.Klassendiagramm als Ergebnis der OOA
[plantuml, {prefix}-klassendiagramm-schalter-lampe, svg]
....
class "Schalter" as schalter1 {
  zustand
  drücken()
} 

class "Lampe" as lampe1 {
  zustand
  einschalten()
  ausschalten()
}

schalter1 "1" --> "*" lampe1 : schaltet
note right on link
  Durch die Multiplizitäten 1 und * am
  Beziehungspfeil wird notiert, dass ein Schalter mit
  mehreren Lampen verbunden werden kann.
end note
....

In einem Klassendiagramm werden Objekte mit derselben Struktur zu einer
Klasse zusammengefasst.
Die Lampen lampe1, lampe2 und lampe3 werden also zu den Klasse `Lampe` zusammengefasst.
Die Nachricht `drücken()` wird
dem Schalter und `ausschalten()` bei der `Lampe` notiert, also jeweils bei der
Klasse, der die entsprechende Nachricht gesendet wird.
Statt Nachricht wird im Zusammenhang mit der Programmsprache
Java der Begriff _Methode_ verwendet.
Die Daten, die auch Attribute der Objekte bzw. Klassen genannt werden,
können im Klassendiagramm mit ihren initialen Werten angegeben werden,
zudem kann auch der entsprechende Datentyp benannt werden
wie in <<klassendiagramm-schema>> und <<klassendiagramm-3>>.

Das Klassendiagramm stellt im Gegensatz zu einem Objektdiagramm keinen
Systemzustand dar, sondern die Struktur der zugrundeliegenden Software
bzw. des Quellcodes.

Die Darstellung einer Klasse im Klassendiagramm folgt dem folgenden Schema:

[[klassendiagramm-schema]]
.Schema der graphischen Darstellung einer Klasse
[plantuml, {prefix}-klassendiagramm-schema, svg]
....
class Klassenname {
  Attribut
  Attribut: Datentyp
  Attribut: Datentyp = Initialwert
  {method} Methode
  Methode(Argumente)
  Methode(Argumente): Ergebnistyp  
}
....

== Objektorientierte Modellierung (OOM)

In der objektorientierten Modellierung werden u.{nbsp}a. die
bereits vorgenommenen Modellierungen in den Klassendiagrammen
verfeinert und z.{nbsp}B. Datentypen und initiale Werte eingefügt.
Gegebenenfalls werden die Diagramme um weitere Klassen ergänzt,
die sich nicht unmittelbar aus der Analyse ergeben haben, aber für
die Implementierung in der gewählten Programmiersprache benötigt werden,
wie die Definition einer Enumeration.


=== Enumerations

In den Objektdiagrammen in <<objektdiagramm-1>> und <<objektdiagramm-2>>
haben die Objekte das
Attribut `zustand` mit den möglichen Werten `ON` und `OFF.`
Anstatt eines vorhandenen Java-Datentyps wie `int`, `boolean` oder `string`
erstellen wir mithilfe einer Aufzählung (engl. enumeration, in Java abgekürzt
zu `enum`)
einen passenden neuen und aussagekräftigen Datentyp.

[[listing-enum-state]]
.Enumumertation State in Java
[source,java]
----
enum State {
  ON,
  OFF
}
----

Die Aufzählung `State` ergänzen wir in dem Klassendiagramm und
verwenden zudem ab jetzt englische Begriffe. Die Verwendung englischer
Sprache im Quellcode ist üblich, da bei den meisten Programmiersprachen
für die Sprachelemente sowie die
https://de.wikipedia.org/wiki/Programmbibliothek[Programmbibliotheken]
ohnehin englische Sprache verwendet wird, wie auch bei Java. 

[[klassendiagramm-2]]
.Klassendiagramm mit Enumeration und englischen Begriffen
[plantuml, {prefix}-klassendiagramm-schalter-lampe-enum, svg]
....
class "Switch" as switch1 {
  state: State
  press()
} 

class "Lamp" as lamp1 {
  state: State
  turnOn()
  turnOff()
}

class "State" << enum >> 
note right
  Eine Enumeration wird in
  Klassendiagrammen mit «enum»
  als besondere Klasse gekennzeichnet.
end note
  

switch1 "1" --> "*" lamp1 : controls
switch1 -> State
lamp1 -> State
....

Sowohl `Switch` als auch `Lamp` verwenden `State`, was durch Pfeile
in <<klassendiagramm-2>> gekennzeichnet ist.

Damit haben wir aus den User-Stories eine objektorientierte Struktur
für die Software entworfen. Man nennt diesen Schritt
https://de.wikipedia.org/wiki/Objektorientierte_Analyse_und_Design[*objektorientierte Modellierung*].

=== Die Aggregation (Hat-Beziehung)

Neben der Assoziation (Kennt-Beziehung) gibt es noch 
stärkere Beziehungstypen, u.{nbsp}a. die
https://de.wikipedia.org/wiki/Assoziation_(UML)#Aggregation_und_Komposition[Aggregation (Hat-Beziehung)] zwischen
Objekten bzw. Klassen.
So _hat_ ein Motorrad ein Vorderrad.

[[objektdiagramm-aggregation]]
.Objektdiagramm mit Aggregation
[plantuml, {prefix}-objektdiagramm-aggregation, svg]
....
object "<u>motorrad1: Motorrad</u>" as m1 

object "<u>vorderrad1: Vorderrad</u>" as v1

m1 o-- v1
note on link
  Das Motorrad <i>hat</i> ein Vorderrad.
end note
....

Die Raute (auch Diamand genannt),
die diesen Beziehungstyp kennzeichnet, darf _nicht_ wie
die Pfeilspitze der Assoziation interpretiert werden, denn die Beziehung
geht vom Motorrad zum Vorderrad.
Auf der Ebene der Programmierung ist bei einer Aggregation die Klasse
Motorrad für die Verwaltung der Objekte der Klasse Vorderrad zuständig.

== Objektorientierte Programmierung (OOP) mit Java

Dem Klassendiagramm entspricht das folgende Java-Programm:

.Java-Programm
[source,java]
----
// Datei State.java
public enum State {
  ON,
  OFF
}

// Datei Switch.java
public class Switch {
  private State state;

  public void press() {
  }      
}

// Datei Lamp.java
public class Lamp {
  private State state;

  public void turnOn() {
  }

  public void turnOff() {
  }      
}       
----

Ist damit die Entwicklung der Software abgeschlossen?
Nein, noch nicht, wir haben bislang erst eine objektorientierte Struktur
erstellt.

=== Was wird noch benötigt, damit der Schalter die Lampen steuert?

.Wir benötigen ...
* Konstruktoren, die wie in den User-Stories den
  Anfangszustand herstellen und Objekte einer Klasse kreieren.

* eine Ausgabe, wenn die Lampe ihren Zustand wechselt, damit wir
  das Programm testen können.

* Quellcode, der die Beziehungen zwischen den Objekten erzeugt.
  Dazu betrachten wir zunächst eine Vereinfachung.

* Quellcode für die Aktionen der Objekte, wenn sie eine Nachricht erhalten,
  das heißt die Methoden
  `press()` in `Switch` sowie
  `turnOn()` sowie `turnOff()` in `Lamp` müssen implementiert werden. 

Wir vereinfachen zunächst die Kennt-Beziehung zwischen `Switch` und
`Lamp` so, dass nur eine `Lamp` mit einem `Switch` verbunden werden kann,
dies nennt man eine _1-zu-1-Beziehung_.

[[klassendiagramm-3]]
.Klassendiagramm mit einer 1-zu-1-Beziehung zwischen `Switch` und `Lamp`.
[plantuml, {prefix}-klassendiagramm-schalter-lampe-vereinfacht, svg]
....
class "State" << enum >> 

class "Switch" as switch1 {
  state: State = OFF
  Switch()
  press()
  connect(Lamp)
  disconnect(Lamp)
} 

class "Lamp" as lamp1 {
  state: State = OFF
  Lamp()
  turnOn()
  turnOff()
}

switch1 -> State
lamp1 -> State

switch1 "1" --> "1" lamp1 : controls
note right on link
  Der Schalter kann jetzt nur
  noch eine Lampe verwenden,
  eine 1-zu-1-Beziehung.
end note
....

In Java muss jede Klassen mit dem
https://de.wikipedia.org/wiki/Zugriffsmodifikator[Zugriffsmodifikator]
`public` jeweils in einer eigenen `java`-Datei,
die den Namen der Klasse trägt, gespeichert werden.

.Java-Programm
[source,java]
----
// State.java
include::src/switch-with-single-lamp/State.java[]

// Datei Lamp.java
include::src/switch-with-single-lamp/Lamp.java[]

// Switch.java
include::src/switch-with-single-lamp/Switch.java[]
----
<1> Hier wird eine Text auf der Konsole ausgegeben. Diese
    setzt sich aus dem aktuellen Objekt `this` sowie dem Text `" ON"`
    zusammen.
<2> Um eine Beziehung von `Switch` zu `Lamp` herstellen zu
    können, wird ein Attribut der Klasse `Lamp` benötigt,
    dieses hat den initialen Wert `null`, d.{nbsp}h. es ist
    anfangs kein Objekt verknüpft.
<3> Die Methoden `turnOn()` und `turnOff()` können nur aufgerufen
    werden, wenn `lamp` mit einem Objekt der Klasse `Lamp` verknüpft ist.
<4> Die Methode `connect()` stellt die Verknüpfung einer Lampe mit einem
    Schalter her.
<5> Eine neue Verknüpfung wird nur dann hergestellt, wenn der
    Schalter noch nicht verbunden ist.
<6> Die Methode `disconnect()` löst eine Verknüpfung zwischen einer Lampe und
    einem Schalter.
<7> Die Verknüpfung wird nur gelöst, wenn die im Parameter angegebene
    `lamp` mit der bereits verknüpften identisch ist.

Mit diesen Klassen können jetzt die Objekte `lamp1` und `switch1` erzeugt werden
und die Lampe `lamp1` mit dem Schalter `switch1` verbunden werden.

.Java-Programm
[source,java]
----
Lamp lamp1 = new Lamp(); <1>
Switch switch1 = new Switch(); <2>
switch1.connect(lamp1); <3>
switch1.press(); <4>
----
<1> Eine neues Objekt der Klasse Lamp mit dem Bezeichner `lamp1` wird erzeugt.
<2> Eine neues Objekt der Klasse Switch mit dem Bezeichner `switch1` wird erzeugt.
<3> Die Lampe `lamp1` wird mit dem Schalter `switch1` verbunden.
<4> {ldquo}Betätigen{rdquo} des Schalters.

Diese Befehle können in
https://www.bluej.org/[BlueJ] auch ohne `main`-Methode
direkt über die Oberfläche oder im integrierten CodePad ausgeführt
werden.
Für ein vollständiges Java-Programm wird hingegen in einer
Klasse eine `main`-Methode benötigt wie in der Klasse `Controller`
im <<final-source-code>>.

=== Wie kann man mehrere Lampen mit einem Schalter verbinden?

Wir benötigen dazu eine Objekt-Sammlung im Switch. In Java gibt es dazu
vorgefertigte Komponenten, z.B. eine
https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html[ArrayList].
Diese hat u.a. die Methoden

`add(E e)`:: Fügt am Ende der Liste ein Objekt hinzu.

`get(int index): E`:: Gibt das Objekt an der angegeben Position `index` aus.

`remove(Object o)`:: Entfernt ein Objekt aus der Sammlung.

Zudem gibt es in Java eine besondere `for`-Schleife für Collections wie
u.{nbsp}a. die ArrayList:

.Java-Programm
[source,java]
....
for (Lamp lamp: lamps) { <1>
  lamp.turnOn(); <2>
}
....
<1> In dem Schleifenkopf wird eine Collection ausgewählt, hier `lamps` sowie
    ein Bezeichner `lamp` der Klasse `Lamp` definiert,
    der nur in dem Schleifenrumpf gültig ist.
<2> Im Schleifenrumpf wirden die Aktionen festgelegt, die mit jedem
    Objekt der Sammlung durchgeführt werden, dazu verwendet man den oben
    definierten Bezeichner `lamp`.

Hier der vollständige Quellcode, der <<user-story-1>> entspricht.:

[[final-source-code]]
.Vollständiges Java-Programm mit Javadoc-Kommentaren
[source,java]
----
// State.java
include::src/switch-with-multiple-lamps/State.java[]

// Lamp.java
include::src/switch-with-multiple-lamps/Lamp.java[]

// Switch.java
include::src/switch-with-multiple-lamps/Switch.java[]

// Controller.java
include::src/switch-with-multiple-lamps/Controller.java[]
----

Der Quellcode wird mit dem Java-Compiler `javac` übersetzt.
Dabei genügt es, die Datei `Controller.java` anzugeben.
Der Java-Compiler übersetzt dann automatisch alle weiteren
benötigten Dateien.

[source,sh]
----
$ javac Controller.java
----

Das Programm wird mit `java` ausgeführt:

[source,sh]
----
$ java Controller
Lamp@6d06d69c ON <1>
Lamp@7852e922 ON
Lamp@4e25154f ON
----
<1> `Lamp@6d06d69c` wird durch `this` in der Ausgabe mit
    `System.out.println(this + " ON");` erzeugt und setzt
    sich aus dem Namen der Klasse und der ID des Objektes zusammen.

