include::../../templates/ovm-header.adoc[]
:ovm-code: IT-AE-JA-LS-5.1
:kind: Lernsituation
:short-title: Einstieg Objektorientierte Entwicklung mit Java
= {ovm-code} {kind} zu Linux Essentials
André Bauer <a.bauer@ovm-kassel.de>
v1.0, 20. Februar 2018


include::../../templates/ovm-head-table.adoc[]

| *Links*
| 

| *Verwandte Literatur*
| IT-AE-JA-JS-5.1

| *Lizenz*
| {cc-by-sa}
|===

== Lichtsteuerung für das SmartHome

Die Hometech GmbH entwickelt Hard- und Software für des SmartHome.
Zur Ziet werden Lösungen für die digital gesteuerte Gebäudebeleuchtung
entwickelt.
Steuerungselemente wie Schalter und Dimmer sollen zukünftig nicht mehr
direkt mit den Lampen verbunden werden. Statt dessen soll eine
programmierbare Steuerungseinheit.


Die HomeSoft AG produziert Produkte im Bereich "SmartHome" und hat Sie
beauftragt, eine Steuerung für Schalter und Lampen zu entwickeln.

Schalter und Lampen sollen als objektorientierte
Software-Module entwickelt werden, so dass nach Bedarf Schalter und
Lampen miteinander verbunden werden können.

=== Aufgabe 1

Entwerfen Sie jeweils ein UML-Objekt-Diagramm für einen Schalter und eine Lampe

[plantuml, diagram-objects, svg]
....
object Schalter
object Lampe 
....


=== Aufgabe 2

Erstellen Sie ein UML-Klassen-Diagramm für einen Dimmer mit den Stufen 0--3.