include::../../templates/ovm-header.adoc[]
:ovm-code: IT-AE-UML-LJ-3.5
:kind: Lernjob
:short-title: Ein Programm mit einem Sequenzdiagramm und einem Objektdiagramm darstellen
= {kind} {ovm-code} {short-title}
André Bauer <a.bauer@ovm-kassel.de>
v1.0, 17. April 2018

include::../../templates/ovm-head-table.adoc[]

| *Links*
a|

Zum Erstellen von UML-Diagrammen bieten sich die Programme
https://wiki.gnome.org/Apps/Dia/[Dia],
https://www.draw.io/[draw.io],
http://www.yworks.com/products/yed[yEd] bzw.
https://www.yworks.com/yed-live/[yEd Live] und
http://plantuml.com/[PlantUML] an, dieses kann in u.{nbsp}a. in
https://en.wikipedia.org/wiki/PlantUML#Applications_that_use_PlantUML[Eclipse und Word als Plugin verwendet werden].

| *Verwandte Literatur*
a|

* IT-AE-UML-INFO-3.1
* IT-AE-UML-INFO-3.3
* http://moodle2013.ovm-kassel.de/mod/url/view.php?id=8428[Infoblatt I-AE-MO-5 "Sequenzdiagramm"]
* https://pdfs.semanticscholar.org/presentation/b024/fbaa3c40ce8e5e6dd47d045b3ce34d44d291.pdf[Vortragsfolien "Modellieren mit der Unified Modeling Language: Klassen- und Objektdiagramme"]

| *Verwandte Lernjobs*
a|

* http://moodle2013.ovm-kassel.de/mod/url/view.php?id=10065[Lernjob LJ-AE-UML-2.5.1 "Seqenzdiagramm-"Bestellvorgang" mit Musterlösung]

| *Lizenz*
| {cc-by-sa}

|===

== {short-title}

Gegeben seien die Klassen `Switch` und `Lamp` sowie die Enumeration `State` in
ihrer abschließenden Fassung aus dem Informationsblatt IT-AE-JA-INFO-5.4.
Betrachten Sie folgenden Quellcode, der die Methode `main` des
Programms ersetzt.

.Java-Quellcode-Fragment
[source,java]
....
public static void main(String args[]) {
  Lamp lamp1 = new Lamp();
  Lamp lamp2 = new Lamp();
  Lamp lamp3 = new Lamp();
  Switch switch1 = new Switch();
  switch1.connect(lamp1);
  switch1.connect(lamp2);
  Switch switch2 = new Switch();
  switch2.connect(lamp2);
  switch2.connect(lamp3);
  switch1.press();
  switch2.press();
}
....

=== Aufgabe 1

Erstellen Sie ein Sequenzdiagramm für die in der `main`-Methode erzeugten
Objekte. +
Als Hilfen können Sie u.{nbsp}a. das 
http://moodle2013.ovm-kassel.de/mod/url/view.php?id=8428[Infoblatt I-AE-MO-5 "Sequenzdiagramm"] sowie den
http://moodle2013.ovm-kassel.de/mod/url/view.php?id=10065[Lernjob LJ-AE-UML-2.5.1 "Seqenzdiagramm-"Bestellvorgang" mit Musterlösung]
verwenden.

=== Aufgabe 2

Fertigen Sie ein Objektdiagramm an, das den System-Zustand zum Ende
der `main`-Methode zeigt.


=== Aufgabe 3

Bewerten Sie anhand Ihrer Lösungen aus den Aufgaben 1 und 2, ob diese
Verbindung aus Schaltern und Lampen ein wünschenswertes
Systemverhalten zeigt.