include::../../templates/ovm-header.adoc[]
:ovm-code: IT-AE-JA-LJ-5.5
:kind: Lernjob
:short-title: Ein Programm mit einem Sequenzdiagramm und einem Objektdiagramm darstellen
= {kind} {ovm-code} {short-title}
André Bauer <a.bauer@ovm-kassel.de>
v1.0, 25. Februar 2018

include::../../templates/ovm-head-table.adoc[]

| *Links*
a|

Zum Erstellen von UML-Diagrammen bieten sich die Programme
https://wiki.gnome.org/Apps/Dia/[Dia],
https://www.draw.io/[draw.io],
http://www.yworks.com/products/yed[yEd] bzw.
https://www.yworks.com/yed-live/[yEd Live] und
http://plantuml.com/[PlantUML] an, dieses kann in u.{nbsp}a. in
https://en.wikipedia.org/wiki/PlantUML#Applications_that_use_PlantUML[Eclipse und Word als Plugin verwendet werden].

| *Verwandte Literatur*
a|

* IT-AE-JA-INFO-5.1
* IT-AE-JA-INFO-5.2| {empty}

| *Lizenz*
| {cc-by-sa}

|===

== {short-title}

Gegeben seien die Klassen `Switch` und `Lamp` sowie die Enumeration `State` in
ihrer abschließenden Fassung aus dem Informationsblatt IT-AE-JA-INFO-5.4.
Betrachten Sie folgenden Quellcode, der die Methode `main` des
Programms ersetzt.

.Java-Quellcode-Fragment
[source,java]
....
public static void main(String args[]) {
  Lamp lamp1 = new Lamp();
  Lamp lamp2 = new Lamp();
  Lamp lamp3 = new Lamp();
  Switch switch1 = new Switch();
  switch1.connect(lamp1);
  switch1.connect(lamp2);
  Switch switch2 = new Switch();
  switch2.connect(lamp2);
  switch2.connect(lamp3);
  switch1.press();
  switch2.press();
}
....

=== Aufgabe 1

Erstellen Sie ein Sequenzdiagramm für die in der `main`-Methode erzeugten
Objekte.


=== Aufgabe 2

Fertigen Sie ein Objektdiagramm an, das den System-Zustand zum Ende
der `main`-Methode zeigt.


=== Aufgabe 3

Bewerten Sie anhand Ihrer Lösungen aus den Aufgaben 1 und 2, ob diese
Verbindung aus Schaltern und Lampen ein wünschenswertes
Systemverhalten zeigt.