include::../../templates/ovm-header.adoc[]
:ovm-code: IT-AE-JA-LJ-5.3
:kind: Lernjob
:short-title: UML-Diagramme auf der Basis einer User-Story erstellen
= {kind} {ovm-code} {short-title}
André Bauer <a.bauer@ovm-kassel.de>
v1.0, 21. Februar 2018

include::../../templates/ovm-head-table.adoc[]

| *Links*
| {empty} 

| *Verwandte Literatur*
| {empty}

| *Lizenz*
| {cc-by-sa}
|===

== {short-title}

.User-Story
****
Anastasia stellt bei ihren Internet-Radiowecker die Weckzeit auf 6:25{nbsp}Uhr,
wählt das Programm super-harmony.fm aus, aktiviert den Wecker und legt sich
schlafen.
Um 0:25{nbsp}Uhr synchronisiert der Wecker seine Uhrzeit mit einem
NTP-Server.
Als der Wecker am nächsten Morgen um 6:25{nbsp}Uhr beginnt, das
Radioprogramm
von super-harmony.fm zu streamen, drückt sie auf die Slummertaste, der
Wecker schweigt und Anastasia schläft weiter.
Als der Wecker nach 5{nbsp}Minuten
wieder Musik spielt, liest Anastasia die Zeit 6:30{nbsp}Uhr vom Display ab,
schaltet sie die Weckfunktion aus und stellt den Sender auf
pure-techno.fm um. Nachdem sie sich umgezogen hat, schaltet sie das Radio
wieder aus.
****

=== Aufgabe 1

Erstellen Sie zu der User-Story ein geeignetes Sequenzdiagramm.

=== Aufgabe 2

Fertigen Sie zu der User-Story zwei Objektdiagramme an, die jeweils
den Zustand der in der User-Story vorkommenden Objekte und Personen
zu unterschiedlichen Zeitpunkten wiedergeben.

=== Aufgabe 3

Erstellen Sie zu der User-Story ein Klassendiagramm auf der Grundlage
Ihres Ergebnisses aus Aufgabe 2.

// === Aufgabe 4

// Geben Sie zu ihrem Klassendiagramm aus Aufgabe 3 den entsprechende
// Java-Quellcode an.


