include::../../templates/ovm-header.adoc[]
:ovm-code: IT-AE-UML-LJ-3.6
:kind: Lernjob
:short-title: Klassendiagramm und Quellcode auf der Grundlage eines Objektdiagramms erstellen
:prefix: ljkdqc
= {kind} {ovm-code} {short-title}
André Bauer <a.bauer@ovm-kassel.de>
v1.0, 17. April 2018

include::../../templates/ovm-head-table.adoc[]

| *Links*
a|

Zum Erstellen von UML-Diagrammen bieten sich die Programme
https://wiki.gnome.org/Apps/Dia/[Dia],
https://www.draw.io/[draw.io],
http://www.yworks.com/products/yed[yEd] bzw.
https://www.yworks.com/yed-live/[yEd Live] und
http://plantuml.com/[PlantUML] an, dieses kann in u.{nbsp}a. in
https://en.wikipedia.org/wiki/PlantUML#Applications_that_use_PlantUML[Eclipse und Word als Plugin verwendet werden].

| *Verwandte Literatur*
a|

* IT-AE-UML-INFO-3.3
* IT-AE-UML-INFO-3.4
* https://pdfs.semanticscholar.org/presentation/b024/fbaa3c40ce8e5e6dd47d045b3ce34d44d291.pdf[Vortragsfolien "Modellieren mit der Unified Modeling Language: Klassen- und Objektdiagramme"]
* http://www.erasmus-reinhold-gymnasium.de/info/prakt_inf/UML-Informatikskript.pdf[Skript "Objektorientierte Programmierung mit Java und UML"]

| *Lizenz*
| {cc-by-sa}
|===

== {short-title}

Drei Mannschaften tragen ein Beachvolleyballturnier aus. Der Stand zum Ende
des Turniers ist in dem folgenden Objektdiagramm festgehalten: 

.Objektdiagramm Beachvolleyballturnier
[graphviz, {prefix}-objektdiagramm-beachvolleyballturnier, {graphviz-format}]
....
digraph G {
    fontname = "Bitstream Vera Sans"
    fontsize = 8
    rankdir = BT

    node [
        fontname = "Bitstream Vera Sans"
        fontsize = 8
        shape = "record"
    ]

    P1 [ label=<{<u>platz1: Spielfeld</u>|name = "Platz 1"}> ]
    
    P2 [ label=<{<u>platz2: Spielfeld</u>|name = "Platz 2"}> ]

    TA [ label=<{<u>aTeam: Mannschaft</u>|name = "A-Team"<br/>trikotfarbe = "rot - blau"}> ]

    TS [ label=<{<u>teamSandsturm: Mannschaft</u>|name = "Sandsturm"<br/>trikotfarbe = "sandgelb"}> ]

    TB [ label=<{<u>dieBallhelden: Mannschaft</u>|name = "Die Ballhelden"<br/>trikotfarbe = "weiß"}> ]

    S3 [ label=<{<u>spielASsatz1: Satz</u>|punkteA = 14<br/>punkteB = 21}> ]

    SAS [ label=<{<u>spielAS: Spiel</u>|start = 12:15 Uhr<br/>ende = 13:50 Uhr }> ]
  
 
    S4 [ label=<{<u>spielASsatz2: Satz</u>|punkteA = 25<br/>punkteB = 23}> ]
  
    S5 [ label=<{<u>spielASsatz3: Satz</u>|punkteA = 14<br/>punkteB = 16}> ]
  
    SAB [ label=<{<u>spielAB: Spiel</u>|start = 14:15 Uhr<br/>ende = 15:20 Uhr}> ]
  

    S1 [ label=<{<u>spielABsatz1: Satz</u>|punkteA = 21<br/>punkteB = 17}> ]


    S2 [ label=<{<u>spielABsatz2: Satz</u>|punkteA = 21<br/>punkteB = 11}> ]

    SBS [ label=<{<u>spielBS: Spiel</u>|start = 16:15 Uhr<br/>ende = 17:10 Uhr}> ]
  
    S6 [ label=<{<u>spielBSsatz1: Satz</u>|punkteA = 6<br/>punkteB = 21}> ]
  
    S7 [ label=<{<u>spielBSsatz2: Satz</u>|punkteA = 19<br/>punkteB = 21}> ]

    edge [
        fontname = "Bitstream Vera Sans"
        fontsize = 8
	arrowhead = "open"
    ]

    SAS -> TA [ label=teamA ]
    SAS -> TS [ label=teamB ]
    SAS -> P1 [ label=platz ]
    
    SAB -> TA [ label=teamA ]
    SAB -> TB [ label=teamB ]
    SAB -> P2 [ label=platz ]

    SBS -> TS [ label=teamA ]
    SBS -> TB [ label=teamB ]
    SBS -> P1 [ label=platz ]

    edge [
        fontname = "Bitstream Vera Sans"
        fontsize = 8
        arrowhead = "odiamond"
    ]

    S3 -> SAS [ label="satz[0]" ]
    S4 -> SAS [ label="satz[1]" ]
    S5 -> SAS [ label="satz[2]" ]

    S1 -> SAB [ label="satz[0]" ]
    S2 -> SAB [ label="satz[1]" ]

    S6 -> SBS [ label="satz[0]" ]
    S7 -> SBS [ label="satz[1]" ]
}
....

=== Aufgabe 1

Erstellen Sie zu dem Objektdiagramm ein Klassendiagramm. +
Als Hilfen können Sie neben den Informationsblättern
IT-AE-UML-INFO-3.3 und IT-AE-UML-INFO-3.4 die Vortragsfolien
https://pdfs.semanticscholar.org/presentation/b024/fbaa3c40ce8e5e6dd47d045b3ce34d44d291.pdf["Modellieren mit der Unified Modeling Language: Klassen- und Objektdiagramme"] verwenden.

=== Aufgabe 2

Geben Sie den Java-Quellcode zu Ihrem Klassendiagramm aus Aufgabe 1 an. +
Als Hilfen bietet sich neben dem Informationsblatt IT-AE-UML-INFO-3.4 das
http://www.erasmus-reinhold-gymnasium.de/info/prakt_inf/UML-Informatikskript.pdf[Skript "Objektorientierte Programmierung mit Java und UML"] (insbesondere die Seiten 77 bis 81) an.

=== Aufgabe 3

Erzeugen Sie in Java die Objekte, die mit dem Objekt `spielAB`
verbunden sind und stellen Sie auch diese Verbindungen in Ihrem
Java-Programm her.