= Teaching materials for information technology and mathematics

See the latest build at https://bauerandre.github.io/unterricht/[].

== LICENSE

* If not declared different in an individual file all documents are licensed
  under a Creative Commons Attribution-ShareAlike 4.0 International License.
  See link:LICENSE.CC-BY-SA[] for details.
* If not declared different in an individual file all source code is
  licensed under THE MIT License. See link:LICENSE.MIT[] for details.

== Installation

You'll need both npm and RubyGems with bundler.

[source,sh]
----
$ sudo apt install npm ruby ruby-bundler
$ sudo ln -s /usr/bin/nodejs /usr/local/bin/node <1>
----
<1> In Ubuntu node is named nodejs, so we need this symbolic link here.

With this prerequisites you can install the project dependencies.

[source,sh]
----
$ git clone https://github.com/bauerandre/unterricht.git
$ cd unterricht
$ npm install
$ sudo npm install -g gulp
$ bundler
$ mkdir -p private/keep/keep
$ touch private/keep/keep/keep.adoc
----

== Usage

With a watch job and browser-sync you can write your AsciiDoc-Files
with your favourite editor and have automated updates in your browser
each time you are saving your work in your editor. 

[source,sh]
----
$ gulp prebuild <1>
$ gulp build <2>
$ npm run sync <3>
$ npm run watch <4>
----
<1> Copies everything from `docs`, `images`, `partials`, `stylesheets`
    and `private` to `_build`
<2> Runs the build once.
<3> Starts `browser-sync`.
<4> Starts a watch job on `docs` and `private` and runs the build job
    on file changes.


== Advanced Usage

=== Asciidoctor Diagrams

To create Diagrams with
https://asciidoctor.org/docs/asciidoctor-diagram/[Asciidoctor Diagram]
you'll need to install the diagram tools and their dependencies with
your package-manager, e.g. PlantUML: 

[source,sh]
----
$ sudo apt install plantuml 
----

=== Prepare publishing

[source,sh]
----
$ gulp publish:copy <1>
$ npm run serve-publish <2>
----
<1> Copies `_build/unterricht` to `_publish`.
<2> Runs WEBrick on http://localhost:5000/[] with `_test-publish` as
    documentroot.