include::partials/ovm-header.adoc[]
:ovm-code: AE-MS-LJ-1.4
:kind: Lernjob
:short-title: Pseudocode und Programmablaufpläne
include::partials/author.adoc[]
:revdate: 10. September 2018
:sectnums:
:sectnumlevels: 2
:stem: latexmath
:documentdir: /unterricht/anwendungsentwicklung/strukturierte-modellierung/

include::partials/ovm-head-table.adoc[]

| *Links*
a|
* https://code2flow.com/app[code2flow]
* http://friedrich-folkmann.de/papdesigner/Hauptseite.html[PapDesigner]

| *Verwandte Lernjobs*
| AE-MS-LJ-1.1 bis 1.3

| *Lizenz*
| {cc-by-sa}
|===

= {kind} {short-title}

== Lineare Strukturen

=== Beispiel {counter:a}: Umrechnung von Pferdestärken in Kilowatt

Bevor die Einheit Watt zur Angabe der Leistung von Maschinen
im amtlichen und geschäftlichen Bereich vorgeschrieben wurde, wurde insb.
für Kraftfahrzeuge die Einheit Pferdestärke (PS) verwendet, die dort auch
heute noch gebräuchlich ist.
Dabei entspricht 1{nbsp}PS einer Leistung von 735,498{nbsp}W.

Das Programm soll eine Angabe in Pferdestärken
in Kilowatt (kW) umrechnen und ausgeben.



==== Pseudocode

.Pseudocode zur Berechnung der Leistung in kW
[source, ruby, linenums]
....
program LeistungVonPSinKW
  read ps
  w := ps * 735.498
  kw := w / 1000
  print kw
end programm LeistungVonPSinKW
....

<<<

==== Programmablaufplan

.Programmablaufplan zur Berechnung der Leistung in kW
[link=https://code2flow.com/HdHJgw]
image::{documentdir}ps-kw-flowdiagram.svg[pdfwidth=16%,width=35%]

==== Java-Quellcode

https://github.com/andrebauer/it-ae-ms-lj-1.4/blob/master/src/LeistungVonPSinKW.java[LeistungVonPSinKW.java]

=== Aufgabe {counter:b}: Fahrradcomputer

Auf dem Display eines Fahrradcomputers sollen die seit dem letzten
Zurücksetzen des Zählers zurückgelegte Strecke sowie die aktuelle
Geschwindigkeit angezeigt werden.

Als Berechnungsgrundlage dienen jeweils der Reifenaußendurchmesser in Zoll
sowie die Anzahl der Umdrehungen. Für die zurückgelegte Strecke
wird die Anzahl seit dem letzten Zurücksetzen des Zählers
gemessen, für die Geschwindigkeit die Anzahl der Umdrehungen in den
letzten drei Sekunden.

[stem]
++++
\begin{align*}
d &= \text{Reifenaußendurchmesser} \\
s &= \text{zurückgelegte Strecke} \\
v &= \text{momentane Geschwindigkeit} \\

s &= d \cdot
\frac{2{,}54 \;\text{cm}}{\text{Zoll}} \cdot \pi \cdot
\text{Umdrehungen} \cdot \frac{\text{m}}{100\;\text{cm}} \\

v &= d \cdot
\frac{2{,}54 \;\text{cm}}{\text{Zoll}} \cdot \pi \cdot
\frac{\text{Umdrehungen}}{3\;\text{s}} \cdot
\frac{60\;\text{s}}{\text{min}} \cdot \frac{60\;\text{min}}{\text{h}} \cdot
\frac{\text{m}}{100\;\text{cm}} \cdot \frac{\text{km}}{1000\;\text{m}}
\end{align*}
++++

<<<
== Mehrfachauswahl

=== Beispiel {counter:a}: Römische Zahlschrift

In die römischen Zahlschrift werden üblicherweise sieben Buchstaben verwendet,
die jeweils einem bestimmten Wert entsprechen.

[width=50%]
|===
| Wert | Zeichen

| 1 | I
| 5 | V
| 10 | X
| 50 | L
| 100 | C
| 500 | D
| 1000 | M

|===

Das folgende Funktion gibt zu einem Wert das entsprechende Zeichen zurück.
Falls es für einen Wert kein Zeichen gibt, wird eine Fehlermeldung
zurückgegeben. Das Beispiel in <<funktion-roemische-zahlen>> ist
als Funktion und nicht als vollständiges
Programm ausgeführt. Die Funktion kann von einen übergeordneten
Programm wie z.{nbsp}B. in dem Programm
in <<aufruf-roemische-zahlen>> mit `call` aufgerufen werden, dabei
wird der Rückgabewert von `roemischesZahlzeichen` an
die Variable `mille` übergeben.

[[aufruf-roemische-zahlen]]
.Pseudocode zum Aufruf der Funktion `roemischesZahlzeichen`
[source, ruby, linenums]
....
program RoemischeZahl
  mille = call roemischesZahlzeichen(1000)
  print "1000 hat das Zahlzeichen " mille
end program RoemischeZahl
....

<<<
==== Pseudocode

[[funktion-roemische-zahlen]]
.Pseudocode zur Funktion `roemischesZahlzeichen`
[source, ruby, linenums]
....
function roemischesZahlzeichen(wert) 
  case wert of 
    1:
      return I
    5:
      return V
    10:
      return X
    50:
      return L
    100:
      return C
    500:
      return D
    1000:
      return M
    default:
      error: "Für den Wert " wert " gibt es kein römisches Zahlzeichen."
....

==== Programmablaufplan

.Programmablaufplan zur Funktion `roemischesZahlzeichen`
[link=https://code2flow.com/U8sIfx]
image::{documentdir}roemisches-zahlzeichen-flowdiagram.svg[pdfwidth=65%,width=65%]

==== Java-Quellcode

https://github.com/andrebauer/it-ae-ms-lj-1.4/blob/master/src/RoemischeZahl.java[RoemischeZahl.java]

=== Aufgabe {counter:b}: TCP-Netzwerkdienste

Eine Funktion soll für eine Auswahl
beliebter TCP-Netzwerkdienste zu der Standard-Portnummer
den entsprechenden Dienstnamen zurückgeben.
Falls die Portnummer unbekannt ist, soll eine entsprechende Fehlermeldung
zurückgegeben werden.

[width=50%]
|===
| Standard-Portnummer | Dienstname

| 20 | ftp
| 22 | ssh
| 25 | smtp
| 53 | domain
| 80 | http
| 110 | pop3
| 443 | https

|===

<<<
== Mehrfache Verzweigung

=== Beispiel {counter:a}: IPv4-Netzklassen

Die IPv4-Adressen haben eine Länge 32-Bit, d.{nbsp}h. vier Byte.
Zur menschenlesbaren Darstellung ist es üblich, die vier Bytes
jeweils im Dezimalsystem, also als Zahl zwischen 0 und 255 darzustellen,
und mit einem Punkt zu trennen.
So hat die Domain ovm-kassel.de die IPv4-Adresse 89.31.143.1.
Anhand der Anfangsbits bzw. des ersten Bytes wurden die
IPv4-Adressen bis 1993 in sogenannte Netzwerkklassen unterteilt.
Anhand der Dezimaldarstellung des ersten Bytes ergibt sich die
folgende Tabelle für die Netzwerkklassen:

[width=50%]
|===
| Bereich | Netzwerkklasse

| 0 {en-dash} 127 | A
| 128 {en-dash} 191 | B
| 192 {en-dash} 223 | C
| 224 {en-dash} 239 | D
| 240 {en-dash} 255 | E

|===

Die IP-Adresse 89.31.143.1 liegt somit in der Netzwerkklasse A.


==== Pseudocode

.Pseudocode zur Bestimmung der Netzwerkklasse
[source, ruby, linenums]
....
program Netzwerkklasse
  read firstByte
  if firstByte < 0 oder firstByte > 255
    error "Ungültige Eingabe"
  if firstByte <= 127
    print "Klasse A"
  elseif firstByte <= 191
    print "Klasse B"
  elseif firstByte <= 223
    print "Klasse C"
  elseif firstByte <= 239
    print "Klasse D"
  else
    print "Klasse E"
end program Netzwerkklasse
....

<<<
==== Programmablaufplan

.Programmablaufplan zur Bestimmung der Netzwerkklasse
[link=https://code2flow.com/NPdgEU]
image::{documentdir}ipv4-class-flowdiagram.svg[pdfwidth=60%,width=65%]

==== Java-Quellcode

https://github.com/andrebauer/it-ae-ms-lj-1.4/blob/master/src/Netzwerkklasse.java[Netzwerkklasse.java]

=== Aufgabe {counter:b}: Helligkeits-Schwellwerte

Eine Mustererkennungssoftware benötigt zu jedem Bildpunkt eine Klassifizierung
anhand der Helligkeit. Die Helligkeit eines Bildpunktes wird
als 10-Bit-Wert, d.{nbsp}h. als Dezimalzahl zwischen 0 und 1023 gemessen.
Die Funktion soll zu der Helligkeit den entsprechende Farbnamen zurückgeben.

[width=50%]
|===
| Helligkeits-Bereich | Farbname

| 0 {en-dash} 149 | schwarz
| 150 {en-dash} 400 | dunkelgrau
| 401 {en-dash} 624 | grau
| 625 {en-dash} 874 | hellgrau 
| 875 {en-dash} 1023 | weiß

|===

<<<
== Anfangsgeprüfte Schleife und Verzweigung

=== Beispiel {counter:a}: Primfaktorzerlegung

Jede natürliche Zahl kann als Produkt von Primzahlen geschrieben werden.
Beispiele:

* stem:[6 = 2 \cdot 3]
* stem:[24 = 2 \cdot 2 \cdot 2 \cdot 3]
* stem:[99 = 3 \cdot 3 \cdot 11]
* stem:[1001 = 7 \cdot 11 \cdot 13]

In einem Programm sollen zu einer gegebenen natürlichen Zahl
die Primfaktoren berechnet und ausgegeben werden.


==== Struktogramm

.Struktogramm zur Primfaktorzerlegung
image::{documentdir}Primfaktorzerlegung.svg[]


<<<
==== Pseudocode

.Pseudocode zur Primfaktorzerlegung
[source, ruby, linenums]
....
program Primfaktorzerlegung
  read n
  t := 2
  while n > 1
    if Ist n durch t ohne Rest teilbar?
      n := n / t
      print t
    else
      t := t + 1
end program Primfaktorzerlegung
....


==== Programmablaufplan

.Programmablaufplan zur Primfaktorzerlegung
[link=https://code2flow.com/znlIQc]
image::{documentdir}primfaktorzerlegung-flowdiagram.svg[pdfwidth=65%,width=65%]

==== Tabellarischer Schreibtischtest

Es wird das Programm mit der Zahl stem:[60 = 2 \cdot 2 \cdot 3 \cdot 5] getestet.

[width=75%]
|===
| Schritt | n | t | Ausgabe | n > 1 | t teilt n

| 0 | 60 | 2 | - | WAHR | WAHR 
| 1 | 30 | 2 | 2 | WAHR | WAHR
| 2 | 15 | 2 | 2 | WAHR | FALSCH
| 3 | 15 | 3 | - | WAHR | WAHR
| 4 | 5 | 3 | 3 | WAHR | FALSCH
| 5 | 5 | 4 | - | WAHR | FALSCH
| 6 | 5 | 5 | - | WAHR | WAHR
| 7 | 1 | 5 | 5 | FALSCH | -
|===

==== Java-Quellcode

https://github.com/andrebauer/it-ae-ms-lj-1.4/blob/master/src/Primfaktorzerlegung.java[Primfaktorzerlegung.java]

=== Aufgabe {counter:b}: Primzahlen

Eine natürliche Zahl ist eine Primzahl,
wenn sie nur durch 1 und durch sich selbst
ohne Rest teilbar ist.

// let rec is_prime_helper n t = if t = n then true else if n mod t = 0 then false else is_prime_helper n (t + 1);;
// let is_prime n = if n > 1 then is_prime_helper n 2 else false;;
// let ns = List.init 1000 id;;
// let primes = List.filter ns ~f:is_prime ;;
// List.iter primes ~f:(fun p -> print_string ((Int.to_string p) ^ " "));;

Die Primzahlen sind
2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, ...

Als einfaches Verfahren, um zu prüfen, ob eine Zahl asciimath:[n] eine Primzahl ist,
kann man daher bei allen Zahlen zwischen 1 und der Zahl asciimath:[n]
testen, ob diese die Zahl asciimath:[n] ohne Rest teilen.
Falls ein Teiler gefunden wurde kann das Verfahren abgebrochen werden,
da die Zahl asciimath:[n] keine Primzahl ist. Falls kein Teiler gefunden wird, ist
die Zahl asciimath:[n] eine Primzahl.

==== Testdaten 

Als Testdaten stehen die https://de.wikibooks.org/wiki/Primzahlen:_Tabelle_der_Primzahlen_(2_-_100.000)[Primzahlen von 2 bis 100.000] zu Verfügung.

== Zählschleife

=== Beispiel {counter:a}: ISBN-10

Bücher werden durch die Internationale Standardbuchnummer (ISBN) eindeutig
gekennzeichnet. Bis 2006 wurde dazu eine zehnstellige Nummer verwendet,
die eine Prüfziffer enthält.
Diese Prüfziffer berechnet man,
indem man die erste Ziffer mit eins multipliziert, die zweite mit zwei
usw. bis zur neunten Ziffer und die Ergebnisse addiert.
Diese Summe wird anschließend durch 11 dividiert. Aus dem Rest dieser
Division wird die Prüfziffer gebildet. Falls der Rest 10 ist, wird das
Zeichen {lsquo}X{rsquo} verwendet.

==== Beispiel: ISBN 3-8171-2004-4

Die ersten neun Ziffern sind 3-8171-2004. 

[stem]
++++
\begin{align*}
3 \cdot 1 + 8 \cdot 2 + 1 \cdot 3 + 7 \cdot 4 + 1 \cdot 5 + 2 \cdot 6 + 0 \cdot 7 + 0 \cdot 8+ 4 \cdot 9 &= 103 \\

103 &= 9 \cdot 11\;\;\text{ Rest }\;\;4
\end{align*}
++++

Daher hat die ISBN 3-8171-2004-4 die Prüfziffer 4.

<<<
==== Pseudocode

Die Ziffern der ISBN werden als Feld Z behandelt. 

.Pseudocode zur Berechnung der Prüfziffer für die ISBN-10
[source, ruby, linenums]
....
program ISBN10CheckDigit
  read Z
  summe := 0
  for i := 1 to 9
    produkt = Z[i] * i
    summe := summe + produkt
  p := Rest der Division zwischen summe und 11
  if p = 10 
    print "X"
  else 
    print p
end program ISBN10CheckDigit
....


==== Programmablaufplan

.Programmablaufplan zur Berechnung der Prüfziffer für die ISBN-10
[link=https://code2flow.com/qFQczf]
image::{documentdir}isbn-10-flowdiagram.svg[pdfwidth=60%,width=65%]

==== tabellarischer Schreibtischtest

Es wird das Programm mit der ISBN 3-8273-7046-9 getestet.

[%autowidth, pdfwidth=75%, width=75%]
|===
| Schritt | Z | i | Z[i] | produkt | summe | p | Ausgabe

| 0 | [3,8,2,7,3,7,0,4,6] | - | - | - | 0 | - | -
| 1 | [3,8,2,7,3,7,0,4,6] | 1 | 3 | 3 | 3 | - | -
| 2 | [3,8,2,7,3,7,0,4,6] | 2 | 8 | 16 | 19 | - | -
| 3 | [3,8,2,7,3,7,0,4,6] | 3 | 2 | 6 | 25 | - | -
| 4 | [3,8,2,7,3,7,0,4,6] | 4 | 7 | 28 | 53 | - | -
| 5 | [3,8,2,7,3,7,0,4,6] | 5 | 3 | 15 | 68 | - | -
| 6 | [3,8,2,7,3,7,0,4,6] | 6 | 7 | 42 | 110 | - | -
| 7 | [3,8,2,7,3,7,0,4,6] | 7 | 0 | 0 | 110 | - | -
| 8 | [3,8,2,7,3,7,0,4,6] | 8 | 4 | 32 | 142 | - | -
| 9 | [3,8,2,7,3,7,0,4,6] | 9 | 6 | 54 | 196 | - | -
| 10 | [3,8,2,7,3,7,0,4,6] | - | - | - | 196 | 9 | 9

|===

==== Java-Quellcode

https://github.com/andrebauer/it-ae-ms-lj-1.4/blob/master/src/ISBN10CheckDigit.java[ISBN10CheckDigit.java]

// ==== Automatisierter Test

// .Pseudocode zum automatisierten Testen der Berechnung der Prüfziffer für die ISBN-10
// [source, ruby, java]
// ....
// 3-89721-230-7
// 3-93258-869-X
// 3-82737-019-1
// 3-89319-375-8
// 1-55860-491-X
// ....


=== Aufgabe {counter:b}: ISBN-13

{ldquo}Zur Berechnung der Prüfziffer bei der ISBN-13 werden alle zwölf
Ziffern der noch unvollständigen ISBN addiert, wobei die Ziffern mit gerader
Position (also die zweite, vierte und so weiter) dreifachen Wert erhalten.
Eine 5 an sechster Stelle beispielsweise fließt also als 15 in den Term ein.
Von dem Ergebnis dieser Addition wird die letzte Stelle bestimmt, die dann
von 10 subtrahiert wird. Bei einem Additionsergebnis von zum Beispiel 124
erhält man also 10 − 4 = 6. Dieses Endergebnis ist die Prüfziffer.
Ist das Endergebnis 10, ist die Prüfziffer 0.{rdquo}footnote:[https://de.wikipedia.org/wiki/Internationale_Standardbuchnummer#ISBN-13[Wikipedia.de: Internationale Standardbuchnummer, Abschnitt 4.2 Formeln zur Berechnung der Prüfziffer -- ISBN-13].]

==== Beispiel: ISBN 978-3-14-235047-9

Die ersten zwölf Ziffern sind 978-3-14-235047.

Summe der Ziffern mit ungerader Position:
[stem]
++++
9 + 8 + 1 + 2 + 5 + 4 = 29
++++

Summe der Ziffern mit gerader Position:
[stem]
++++
7 + 3 + 4 + 3 + 0 + 7 = 24
++++

[stem]
++++
\begin{align*}
&\text{Prüfsumme:}\quad 29 + 3 \cdot 24 = 10\mathbf{1} \\
&\text{Prüfziffer:}\quad 10 - \mathbf{1} = 9
\end{align*}
++++




