include::partials/ovm-header.adoc[]
:ovm-code: IT-BS-VM-LJ-3.1
:kind: Lernjob
:short-title: Dokumentieren mit Script und Asciidoctor
:experimental:
include::partials/author.adoc[]
:revdate: 13. Mai 2018

include::partials/ovm-head-table.adoc[]

| *Links*
a|

* https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer’s Guide]
* https://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]
* https://asciidoctor.org/docs/asciidoctor-diagram/[Asciidoctor Diagram]
* https://asciidoctor.org/docs/asciidoctor-pdf/[Asciidoctor PDF]
* http://plantuml.com/[PlantUML]
* http://blockdiag.com/en/[blockdiag, seqdiag, actdiag, nwdiag]

| *Lizenz*
| {cc-by-sa}
|=== 

= {short-title}

{empty}

== Shell-Sessions mit Script documentieren

Shell-Sessions können unter Linux mit
dem Programm `script` aufgezeichnet werden.

.Aufzeichnung einer Shell-Session mit `script`
====
[source]
----
$ script session1.log <1>
Skript gestartet, die Datei ist session1.log
$ ssh andre@192.168.178.28 
andre@192.168.178.28's password: 
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.10.0-28-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

Last login: Thu May 10 18:58:28 2018 from 192.168.178.21
andre@andre-VirtualBox:~$ ls
Bilder     Downloads  Öffentlich    srv     Vorlagen
Dokumente  Musik      Schreibtisch  Videos
andre@andre-VirtualBox:~$ Abgemeldet <2>
Connection to 192.168.178.28 closed.
[andre@triton themenwochen]$ exit <3>
exit
Skript wurde beendet, die Datei ist session1.log 
----
<1> Startet `script` und speichert die Aufzeichnung in der
    Datei `session1.log`.
<2> Die SSH-Session wird mit kbd:[Strg+D] oder `exit` beendet.   
<3> `script` wird mit `exit` beendet.    
====

Das Ergebnis kann mit `cat` angezeigt werden oder mit
einem Texteditor wie z.{nbsp}B. GNU nano, gedit,
emacs, vim, atom oder anderen bearbeitet, kommentiert
und z.{nbsp}B. Teil eines AsciiDoc-Dokuments werden (s.{nbsp}u.). 

.Ausgabe der mit Script gespeicherten Shell-Session
====
[souce, sh]
----
$ cat session1.log 
Script started on 2018-05-11 08:03:35+02:00
[andre@triton themenwochen]$ ssh andre@192.168.178.28
andre@192.168.178.28's password: 
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.10.0-28-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

Last login: Thu May 10 18:58:28 2018 from 192.168.178.21
andre@andre-VirtualBox:~$ ls
Bilder     Downloads  Öffentlich    srv     Vorlagen
Dokumente  Musik      Schreibtisch  Videos
andre@andre-VirtualBox:~$ Abgemeldet
Connection to 192.168.178.28 closed.
[andre@triton themenwochen]$ exit
exit

Script done on 2018-05-11 08:04:13+02:00
----
====

****
*Aufgabe {counter:a}*

Starten Sie die Aufzeichnung einer Shell-Session in einer Linux-VM und
führen Sie die folgenden Arbeitschritte durch:

. Erstellen Sie den Ordner `script-docs` mit `mkdir`.
. Legen Sie in diesem Ordner die Dateien `hello.adoc` und `ad.adoc`
  mit `touch` an.
. Fügen Sie `"Hallo Script"` der Datei `hello.adoc` mit
  `echo "Hallo Script" >> script-docs/hello.adoc` an.
. Fügen Sie der Datei `ad.adoc` die Zeile `"Asciidoctor"` an.
. Lassen Sie mit `ls -l` den Inhalt des Ordners `script-docs` ausgeben
  und beenden Sie Script.

Überprüfen Sie anschließend mit `cat`, ob die Aufzeichnung erfolgreich war.
****

== Asciidoctor

https://de.wikipedia.org/wiki/AsciiDoc[AsciiDoc] ist eine
leichtgewichtige Markup-Sprache, wie z.{nbsp}B. auch
https://de.wikipedia.org/wiki/Markdown[Markdown]. +
http://asciidoctor.org[Asciidoctor] ist eine Ruby-Anwendung,
die AsciiDoc-Dokumente in HTML5, PDF und andere Formate
umwandelt.

Ein AsciiDoc-Dokument wird mit einem Texteditor wie GNU nano, gedit,
emacs, vim, atom oder anderen verfasst bzw. bearbeitet
-- Textverarbeitungsprogramme wie Word oder Writer sind nicht geeignet.
Anschließend werden die AsciiDoc-Dateien in
ein Ausgabeformat übersetzt wie PDF, HTML5, Docbook oder andere.

=== Installation 

Für Asciidoctor wird das Paket `ruby` benötigt:

[source, sh]
----
$ sudo apt update
$ sudo apt install ruby
----

Mit dem Paket `ruby` wird auch
https://de.wikipedia.org/wiki/RubyGems[RubyGems],
das Paketsystem für Ruby installiert, dass zur Installation von
`asciidoctor` verwendet wird.


[source,sh]
----
$ sudo gem install asciidoctor asciidoctor-diagram <1>
$ sudo apt update
$ sudo apt install plantuml
$ mkdir srv
$ cd srv
$ nano index.adoc
$ asciidoctor -r asciidoctor-diagram -b html index.adoc <2>
----
<1> Installation von Asciidoctor und Asciidoctor Diagram mit RubyGems.
<2> Mit `-r asciidoctor-diagram` wir die Erweiterung
    https://asciidoctor.org/docs/asciidoctor-diagram/[Asciidoctor Diagram]
    verwendet.							  

=== Erste Schritte

.Beispiel für ein AsciiDoc-Dokument
====

[source,asciidoc]
-----
include::docs/betriebssysteme/virtualisierung/asciidoc-basis-beispiel-code.adoc[] 
-----
<1> Dokumentitel
<1> Überschriften werden mit zwei oder mehrere `=`-Zeichen eingeleitet.
<4> In den eckigen Klammern kann nach der Angabe `source`
    die verwendete Sprache, wie z.{nbsp}B. `java` oder `sh` für Shell,
    eingetragen werden. Dadurch wir die
    https://de.wikipedia.org/wiki/Syntaxhervorhebung[Syntax farblich hervorgehoben].
<5> Source-Code wird mit mit vier Strichen eingegrenzt.
====

.Beispiel eines mit Asciidoctor generieten HTML5-Dokumentes
====
image::/docs/betriebssysteme/virtualisierung/asciidoc-basis-beispiel.svg[]
====

=== Diagramme mit Asciidoctor erstellen

==== PlantUML

http://plantuml.com/[PlantUML] ist eine Werkzeug, um (UML-)Diagramme zu
erstellen. Über die Erweiterung `asciidoctor-diagram` kann man
PlantUML-Diagramme direkt in AsciiDoc-Dokumenten beschreiben.
Diese werden in
https://de.wikipedia.org/wiki/Portable_Network_Graphics[PNG-Grafiken] uder
https://de.wikipedia.org/wiki/Scalable_Vector_Graphics[SVG-Grafiken]
übersetzt.

Für PlantUML gibt es u.{nbsp}B. Plug-Ins für
http://plantuml.com/eclipse[Eclispe] und
https://plugins.jetbrains.com/plugin/7017-plantuml-integration[Jet Brains Programme wie IntelliJ IDEA].

.Beispiel für die Verwendung von PlantUML in einem AsciiDoc-Dokument
====
[source,asciidoc]
-----
== Assoziation zwischen den Klassen A und B

[plantuml,class-assoziation,svg] <1>
.... <2>
class A

class B

A -up-> B 
....

-----
<1> In den eckigen Klammern wird das Diagrammwerkzeug, der Dateiname und
    das Zielformat festgelegt. Hier wird die Diagramm-Beschreibung mit PlantUML
    in eine SVG-Grafik übersetzt und in der Datei `class-assoziation.svg` 
    gespeichert.     
<2> Diagramm-Beschreibungen werden mit mit vier Punkten eingegrenzt. 
====

==== blockdiag, actdiag, nwdiag und seqdiag

Die Programme
http://blockdiag.com/en/[blockdiag, seqdiag, actdiag und nwdiag]
übersetzen --{nbsp}ähnlich wie PlantUML{nbsp}-- Diagramm-Beschreibungen
in Grafiken.

Sie können unter Ubuntu über das Paktemanagment-System installiert werden:

----
$ sudo apt update
$ sudo apt install python-blockdiag python-actdiag python-nwdiag python-seqdiag
----

=== PDF-Dokumente generieren

PDF-Dokumente werden aus Asciidoc-Dokumenten durch Angabge der Erweiterung
mit `-r asciidoctor-pdf` und des Ausgabeformats mit `-b pdf`
generiert.

==== Installation

[source, sh]
----
$ sudo gem install asciidoctor-pdf --pre
----

==== Anwendung

[source, sh]
----
$ asciidoctor -r asciidoctor-diagram -r asciidoctor-pdf -b pdf -a allow-uri-read index.adoc
----

Für PDF-Dokumente gibt es unter Linux verschiedenen Viewer wie `evince`
oder `atril`, die die Dokumente nach Änderungen automatisch neu laden.

[source, sh]
----
$ evince index.pdf
----