= Desktop-Virtualisierung mit Virtualbox
André Bauer <a.bauer@ovm-kassel.de>
v1.0, 13. Februar 2018
:doctype: article
:reproducible:
:stem: latexmath
:source-highlighter: pygments
:listing-caption: Listing
:imagesoutdir: generated
:imagesdir: images
:oimagesdir: {imagesdir}

== Was ist Virtualiserung?

:imagesdir: {imagesoutdir}

[ditaa, virtualisierung, separation=false]
....
+-------------------------------------------+
| +-----------+ +-----------+ +-----------+ |
| | Anwendung | | Anwendung | | Anwendung | |
| +-----------+ +-----------+ +-----------+ |
| | Gast–BS   | | Gast–BS   | | Gast–BS   | |
| | (Windows) | | (Linux)   | | (Solaris) | |
| +-----------+ +-----------+ +-----------+ |
| | Virtuelle | | Virtuelle | | Virtuelle | |
| | Maschine  | | Maschine  | | Maschine  | |
| +-----------+ +-----------+ +-----------+ |
+-------------------------------------------+
| +---------------------------------------+ |
| |       Virtualiserungsoftware          | |
| +---------------------------------------+ |
| |         Host–Betriebssystem           | |
| +---------------------------------------+ |
| |         Physische Maschine            | |
| +---------------------------------------+ |
+-------------------------------------------+
....

:imagesdir: {oimagesdir}

Virtualisierung erlaubt es, mehrere Gast-Betriebssysteme gleichzeitig auf einer physischen Maschine zu betreiben. Dank der Hardwareunterstützung heutiger Prozessoren besteht für die Gast-Betriebssysteme kein spürbarer Geschwindigkeitsnachteil mehr gegenüber dem Host-Betriebssystem.

== Virtualiserung im BIOS aktivieren

Bitte erst prüfen, ob die Hardwareunterstützung der Virtualisierung bereits aktiviert. Unter Windows 10 kann dies im Task-Manager unter "Leistung" geprüft werden. Gegebenenfalls kann dann dieser Schritt übersprungen werden.

* http://daily-experiences.com/intel-virtualisierung-technologie-auf-windows-10-im-bios-aktivieren/#.WoC1LUso9pg[Intel Virtualisierung-Technologie auf Windows 10 im BIOS aktivieren]

* https://docs-old.fedoraproject.org/de-DE/Fedora/12/html/Virtualization_Guide/sect-Virtualization_Guide-Troubleshooting-Enabling_Intel_VT_and_AMD_V_virtualization_hardware_extensions_in_BIOS.html[Aktivieren der Intel VT und AMD-V Virtualisierungs-Hardware-Erweiterungen im BIOS]

* https://www.thomas-krenn.com/de/wiki/Virtualisierungsfunktion_Intel_VT-x_aktivieren[Virtualisierungsfunktion Intel VT-x aktivieren]

== Virtualbox

Virtualbox ist eine Virtualiserungsoftware, die Vollvirtualisierung erlaubt, so dass unveränderte Betriebssysteme als Gast-Betriebssysteme verwendet werden. Zudem kann auch die graphische Oberfläche des Gast-Betriebssystems (in einem Fenster) genutzt werden. Virtualbox stellt die virtuelle Maschinen für die Gast-Systeme bereit und stellt dem Gast-System je nach Konfiguration Ressourcen (Speicher, CPU, Zugriff auf Hardware usw.) des Host-Systems zur Verfügung. 

* https://www.thomas-krenn.com/de/wiki/VirtualBox_installieren[Virtualbox installieren]

== Ubuntu-Linux in Virtualbox installieren

Ubuntu ist eine verbreitete Linux-Distribution und wird für den Linux-Essentials-Kurs der Cisco Network Academy verwendet. 

* https://de.wikihow.com/Ubuntu-in-VirtualBox-installieren[Ubuntu in Virtualbox installieren]