include::docs/templates/ovm-header.adoc[]
:ovm-code: IT-BS-LE-VF-2.1
:kind: Vortragsfolien
:short-title: LPI Linux Essentials: 2. Themenwoche 
:prefix: le-slides-2
:pygments-linenums-mode: inline
:exampledir: docs/betriebssysteme/linux-essentials/slides/
= {short-title}
André Bauer
v1.0, 18. März 2018

== Linux-Distributionen

* https://upload.wikimedia.org/wikipedia/commons/1/1b/Linux_Distribution_Timeline.svg[Linux Distribution Timeline]

* https://distrowatch.com/[]


== Server-Anwendungen (1)

[%autowidth]
[cols="2*", frame=topbot, grid=all]
|===

| Webserver | Apache, Nginx

| Mail Transfer Agent (MTA) | sendmail, Postfix

| Mail Delivery Agent (MDA) | procmail, maildrop

| POP/IMAP server | Dovecot, Cyrus IMAP

| File Sharing | Samba, Netatalk, NFS
|===

=== Server-Anwendungen (2)

[cols="2*"]
|===

| Domain Name System | bind

| LDAP | OpenLDAP

| DHCP | ISC DHCP server

| Relationale Datenbank | MySQL, PostgreSQL

|===

== Command Line Interface (CLI)

Prompt

[source,sh]
----
user@linuxhost:~$
----

Kommando-Syntax

[source,sh]
----
command [options] [arguments]
----

Beipsiel
[source,sh]
----
$ ls -l /usr/bin/perl
-rwxr-xr-x 1 root root 10024  5. Jan 03:53 /usr/bin/perl
----

// == Kommandos (1)

// * date
// * cal
// * history
// * echo
// * env
// * grep
// * which

// === Kommandos (2)

// * type
// * alias

== Globbing: Asterisk (`*`)

[source,sh]
----
$ $ echo /etc/t*
/etc/texmf /etc/tmpfiles.d /etc/trusted-key.key /etc/ts.conf
----

[source,sh]
----
$ echo /etc/*d.d
/etc/depmod.d /etc/modules-load.d /etc/xinetd.d
----

[source,sh]
----
$ echo /etc/r*.conf
/etc/request-key.conf /etc/resolv.conf /etc/resolvconf.conf /etc/rsyncd.conf
----

=== Globbing: Question Mark (`?`)

[source,sh]
----
$ echo /etc/t??????
/etc/ts.conf
----

=== Globbing: Brackets (`[]`)

[source,sh]
----
$ echo /etc/[wy]*
/etc/wgetrc /etc/yaourtrc
----

[source,sh]
----
$ echo /etc/[x-z]*
/etc/X11 /etc/xdg /etc/xinetd.d /etc/xml /etc/xrdb /etc/yaourtrc
----

[source,sh]
----
$ echo /etc/*[6-9]
/etc/ImageMagick-6 /etc/ImageMagick-7 /etc/java-jdk9
----

=== Globbing: Exclamation Point (`!`)

[source,sh]
----
$ echo /etc/[!a-w]*
/etc/X11 /etc/xdg /etc/xinetd.d /etc/xml /etc/xrdb /etc/yaourtrc
----

== Quoting: Double Quotes

[source,sh]
----
$ echo "/etc/[!a-w]*"
/etc/[!a-w]*
----

[source,sh]
----
$ echo "The Shell is $SHELL"
The Shell is /bin/bash
----

=== Quoting: Single Quotes

[source,sh]
----
$ echo 'The Shell is $SHELL'
The Shell is $SHELL
----

=== Quoting: Backslash (`\`)

[source,sh]
----
$ echo "The Shell is \$SHELL"
The Shell is $SHELL
----

=== Quoting: Back Quotes

[source,sh]
----
$ echo "You are here: `pwd`"
You are here: /home/user
----

// == Control Statements


== Hilfe-Systeme

* `man`-Pages
* `info`-Dokumentation
* `--help`-Option
* `apropos`
* `whatis`

// == Dateien und Verzeichnisse

// * absolute Pfade
// * relative Pfade

== Erweiterte Reguläre Ausdrücke

[cols="15,85"]
|===

| `.` | Ein beliebiges einzelnes Zeichen

| `?` | Der vorherige Ausdruck kann, muss aber nicht, einmal vorkommen

| `*` | Der vorherige Ausdruck kann, muss aber nicht,
      	mehrfach wiederholt werden.

| `+` | Der vorherige Ausdruck muss mindestens einmal wiederholt werden.

|===


=== Beispiele

[source,sh]
----
$ cat example.txt
include::{exampledir}example.txt[]
----

[source,sh]
----
$ egrep -n --color '.aa?' example.txt 
2:xyzabc
3:aaaxyz
4:aaxyzdd
----

[source,sh]
----
$ egrep -n --color 'a+x' example.txt 
3:aaaxyz
4:aaxyzdd
----

[source,sh]
----
$ egrep -n --color 'aaa*xyz' example.txt 
3:aaaxyz
4:aaxyzdd
----


=== Erweiterte Reguläre Ausdrücke

[cols="15,85"]
|===

| `[ ]` | Eine Liste oder ein Bereich von Zeichen, +
     	  `^` negiert die Liste

| `^` | Der folgende Ausdruck muss am Anfang einer Zeile vorkommen

| `$` |	Der vorgehende Ausdruck muss an Ende einer Zeile vorkommen

|===

=== Beispiele

[source,sh]
----
$ cat example.txt
include::{exampledir}example.txt[]
----

[source,sh]
----
$ egrep -n --color '^xyz' example.txt 
2:xyzabc
----

[source,sh]
----
$ egrep -n --color 'xyz$' example.txt 
3:aaaxyz
----

[source,sh]
----
$ egrep -n --color '^[a-c]+xyz' example.txt 
3:aaaxyz
4:aaxyzdd
----

[source,sh]
----
$ egrep -n --color '^[^a-c]+xyz' example.txt 
5:eexyzf
----

=== Erweiterte Reguläre Ausdrücke

[cols="15,85"]
|===

| `( )` | Gruppieren von Ausdrücken

| `\|` | Logische ODER-Verknüpfung von Ausdrücken

| `{n}` | Der vorgehende Ausdruck muss genau `n`-mal vorkommen

| `{n,m}` | Der vorgehende Ausdruck darf mindestens `n`-mal,
  	    höchstens `m`-mal vorkommen

|===

=== Beispiele

[source,sh]
----
$ cat example.txt
include::{exampledir}example.txt[]
----

[source,sh]
----
$ egrep -n --color '^[abc]*xyz$|^xyz' example.txt 
2:xyzabc
3:aaaxyz
----

[source,sh]
----
$ egrep -n --color '(^[abc]*xyz$)|(^xyz)' example.txt
2:xyzabc
3:aaaxyz
----

[source,sh]
----
$ egrep -n --color '^[^cd]{4}[zd]{3}' example.txt
4:aaxyzdd
----

[source,sh]
----
$ egrep -n --color '^[^cd]{4}[yzd]{2,3}' example.txt
3:aaaxyz
4:aaxyzdd
----

== Organisatorisches

* Dokumentation im E-Portfolio, siehe Lernsituation IT-BS-LE-LS-2.1
* Test am Ende dieser Themenwoche über die NDG-Linux-Essentials-Module 1-12